<?php
// $Id$


/**
 * @file
 * Code for OS Blog module
 */
include_once 'os_blog.features.inc';

/**
 * Implements hook_process_hook() for node.
 *
 * Removes the username from $submitted info on blog type nodes.
 */
function os_blog_process_node(&$vars) {
  if ($vars['type'] !== 'blog') {
    return;
  }

  // Adds class 'os-log-add-comment' for custom icon on comment link.
  if (isset($vars['content']['links']['comment']['#links']['comment-add'])) {
    if (isset($vars['content']['links']['comment']['#links']['comment-add']['attributes'])) {
      if (isset($vars['content']['links']['comment']['#links']['comment-add']['attributes']['class'])) {
        $vars['content']['links']['comment']['#links']['comment-add']['attributes']['class'] .= ' os-blog-add-comment';
      }
      else {
        $vars['content']['links']['comment']['#links']['comment-add']['attributes']['class'] = 'os-blog-add-comment';
      }
    }
    else {
      $vars['content']['links']['comment']['#links']['comment-add']['attributes'] = array(
        'class' => 'os-blog-add-comment',
      );
    }
  }

  // Builds the submitted variable used by default in node templates
  $pubdate = format_date($vars['created'], 'custom', 'F j, Y');
  // Publication date, formatted with time element
  $vars['submitted'] = '<time datetime="' . $vars['datetime'] . '" pubdate="pubdate">' . $pubdate . '</time>';
}

/**
 * Implements hook_vsite_og_node_type_info().
 */
function os_blog_vsite_og_node_type_info() {
  return array(
    'blog' => 'group content',
  );
}

/**
 * Implements hook_os_widget().
 *
 * Exposes blocks as OpenScholar widgets.
 */
function os_blog_os_widget() {
  $items = array();

  // Displays "Archive" list of blog entry nodes by month
  $items['views-os_blog-block'] = array(
    'module' => 'views',
    'delta' => 'os_blog-block',
    'region' => 'sidebar_second',
    'weight' => '-10',
    'info' => 'Blog Archive',
  );

  return $items;
}

