<?php
/**
 * @file
 * Code for OS Blog module
 */
include_once 'os_blog.features.inc';

/**
 * Implements hook_process_hook() for node.
 *
 * Removes the username from $submitted info on blog type nodes.
 */
function os_blog_process_node(&$variables) {
  if ($variables['type'] !== 'blog') return;

  $variables['submitted'] = _os_blog_format_submitted($variables['submitted']);
}

/**
 * Implements hook_os_widget().
 * 
 * Exposes blocks as OpenScholar widgets.
 */
function os_blog_os_widget() {
  $items = array();
  
  // Displays "Archive" list of blog entry nodes by month
  $items['views-os_blog-block'] = array(
      'module' => 'views', 
      'delta' => 'os_blog-block', 
      'region' => 'sidebar_second', 
      'weight' => '-10',
      'info' => 'Blog Archive'
  );
  
  return $items;
}

/**
 * Strips the username from $submitted display.
 * 
 * Preserves nice HTML5 microformat time markup and default time display.
 * @param string $original
 *   A string like  "Submitted by <a>user</a> on <time>date</time>"
 * @return string $updated
 *   A string like  "Submitted on <time>date</time>"
 */
function _os_blog_format_submitted($original) {
  // Removes user link
  $updated = strip_tags($original, '<time>');

  // Preserves time tag
  $time_position = strpos($updated, '<time');
  if ($time_position === FALSE) return $original;
  
  $updated = 'Submitted on ' . substr($updated, $time_position);

  return $updated;
}