<?php
/**
 * @file
 */

function os_wysiwyg_wysiwyg_editor_settings_alter(&$settings, $context) {

  // settings there are no UI options for
  $settings['gecko_spellcheck'] = true;
  drupal_add_css(drupal_get_path('module', 'os_wysiwyg').'/os_wysiwyg.css');

  // reorder buttons
  // TODO: remove when WYSIWYG module can do this for us

  // format select buttons
  $btns = explode(',', $settings['theme_advanced_buttons1']);
  $format_start = array_search('formatselect', $btns);
  $selects = array_splice($btns, $format_start, 4);
  $format_start = array_search('pasteword', $btns);
  array_splice($btns, $format_start, 0, $selects);

  // toggle toolbar button
  $toggle_start = array_search('pdw', $btns);
  $toggle = array_splice($btns, $toggle_start, 1);
  array_splice($btns, $format_start, 0, $toggle);

  $settings['theme_advanced_buttons1'] = implode(',',$btns);
}

/**
 * Implements hook_media_browser_plugins_alter.
 * Removes the default library from the Media browser. A View has replaced it.
 */
function os_wysiwyg_media_browser_plugins_alter(&$plugins) {
  unset($plugins['library']);
}

/**
 * Adds the pdw plugin to the wysiwyg
 */
function os_wysiwyg_wysiwyg_include_directory($type) {
  if ($type == 'plugins') {
    return $type;
  }
}