<?php
/**
 * @file
 * Code for the OS Software feature.
 */

include_once 'os_software.features.inc';

/**
 * Drupal hooks
 */

/**
 * Implements hook_node_insert()
 * 
 * Enforces single recommended release per project constraint for "Software Release" 
 */
function os_software_node_insert($node) {
  if ($node->type !== 'software_release') return;
  
  $recommended_value = $node->field_software_recommended['und'][0]['value'];
  if ($recommended_value === 0) return;
  
  _os_software_new_recommended_release($node);
}

/**
 * Implements hook_node_update()
 * 
 * Enforces single recommended release per project constraint for "Software Release" 
 */
function os_software_node_update($node) {
  if ($node->type !== 'software_release') return;
  
  // Compares original and updated "Recommended" field value
  $node_original = node_load($node->nid);
  if (isset($node_original->title)) { // Only compare values if an original node exists
    $node_updated = $node;
    
    $recommended_value_original = $node_original->field_software_recommended['und'][0]['value'];
    $recommended_value_updated = $node_updated->field_software_recommended['und'][0]['value'];
    if ($recommended_value_updated === $recommended_value_original) return;
  }  
  // Only updates other Software Release nodes if this value has changed to "Recommended"
  if ($recommended_value_updated === 0) return;
  
  _os_software_new_recommended_release($node);
}


/**
 * Implements hook_node_presave()
 * 
 * Generates the node title for Software Releases 
 */
function os_software_node_presave($node) {
  if ($node->type !== 'software_release') return;
  
  // Sets the node title like "[project-node:title] [release-node:version]"
  $title = _os_software_prepare_release_title($node);
  $node->title = $title;
}

/**
 * Implements hook_node_view()
 * 
 * Sets the custom release node title 
 */
function os_software_node_view($node, $view_mode, $langcode) {  
  if ($node->type !== 'software_release') return;
  
  // Add inline contextual links for "Add new > Software Release"
  $release_type = 'software_release';
  
  $links = array(
    $release_type => array(
      'href' => 'node/add/' . str_replace('_', '-', $release_type) . '?field_software_project=' . $node->nid,
      'title' => ucwords(str_replace('_', ' ', $release_type)),
    ),
  );
  
  $node->content['controls'] = array(
    '#type' => 'container',
    '#weight' => 1,
    '#attributes' => array(
      'class' => array(
        'contextual-controls-wrapper'
      ),
    ),
  );
  $node->content['controls']['add_new'] = array(
    '#theme' => 'ctools_dropdown',
    '#links' => $links,
    '#title' => t('Add New'),
    '#class' => 'add_new',
    '#access' => spaces_access_admin(),
  );
  
  if ($view_mode !== 'full' || TRUE) return;
  
  // Prepares and sets the page body title (<h1>) and head title (<title>)
  $append_sitename = TRUE;
  $title = _os_software_prepare_release_title($node, $append_sitename);
  drupal_set_title($title);
  
  // Prepares "Add new > Software Release" contextual dropdown on node
}

/**
 * Implements hook_node_delete()
 */
function os_software_node_delete($node) {
  if ($node->type !== 'software_project') return;
  // @TODO Delete all referencing software release nodes
}

/**
 * Implements hook_theme()
 */
function os_software_theme() {
  return array();
  // @TODO Define custom template for Software Release node view.
}

/**
 * OpenScholar hooks
 */

/**
 * Implements hook_os_widget()
 * 
 * Exposes blocks as OpenScholar widgets.
 */
function os_software_os_widget() {
  $items = array();
  
  $items['views-os_software_releases-block'] = array(
    'module' => 'views', 
    'delta' => 'os_software_releases-block', 
    'region' => 'sidebar_second', 
    'weight' => '-10',
    'info' => 'All Recent Releases',
  );
  
  return $items;
}

/**
 * Custom functions
 */

/**
 * Finds other recommended releases, marks them "Not recommended"
 */
function _os_software_new_recommended_release($node) {
  // Uses [:os_software_relesases:] view to filter only valid releases for this project
  $view = views_get_view('os_software_releases');
  $view->set_arguments(array($node->field_software_project['und'][0]['target_id']));
  $view->execute('block_1');
  foreach ($view->result as $data) {
    if (!isset($node->nid) || $data->nid !== $node->nid) {
      $release_node = node_load($data->nid);
      $release_node->field_software_recommended['und'][0]['value'] = 0;
      $release_node->path['pathauto'] = ''; // Prevents pathauto from aliasing on save
      node_save($release_node);
    }
  }
}

/**
 * Prepares Software Release node title for presave and view
 */
function _os_software_prepare_release_title($node, $append_sitename = FALSE) {
  $default_prefix = 'Project Release';
  
  $project_node = node_load($node->field_software_project['und'][0]['target_id']);
  $project_title = (!empty($project_node->title)) ? $project_node->title : $default_prefix;
  $version = trim($node->field_software_version['und'][0]['value']);

  $title_parts = array(
    $project_title,
    $version,
  );
  
  if ($append_sitename) {
    $sitename = trim(drupal_get_title);
    $separator = '|';
    $title_parts[] = $separator;
    $title_parts[] = $sitename;
  }
  
  return implode(' ', $title_parts);
}