<?php

include_once 'os_reader.features.inc';

/**
 * Implements hook_init().
 *
 * TODO: Find a way to add the library in the view callback.
 */
function os_reader_init() {
  $menu = menu_get_item();

  if ($menu['path'] != 'os-reader') {
    return;
  }

  drupal_add_library('system', 'drupal.ajax');
}

/**
 * Implements hook_menu().
 */
function os_reader_menu() {
  $items = array();


  // When using %node or %os_feed_item the page callback isn't invoked.
  $items['ajax/os-reader/copy-feed-to-news/%/%/%'] = array(
    'delivery callback' => 'ajax_deliver',
    'type' => MENU_CALLBACK,
    'page callback' => 'os_reader_ajax_copy_feed_to_news',
    'page arguments' => array(3, 4, 5),
    'access callback' => TRUE,
  );

  $items['admin/config/content/os_feed'] = array(
    'title' => 'OS feed config',
    'description' => 'Manage os config',
    'access arguments' => array('os_feed manage'),
    'page callback' => 'os_reader_config',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function os_reader_permission() {
  return array(
    'os_feed manage' => array(
      'title' => t('Mange OS feed item fields'),
      'description' => t('Manage fields of the OS feed item entity.'),
    ),
  );
}

/**
 * Page callback - for now it's empty but it's needed for display the tabs of
 * the field UI module.
 */
function os_reader_config() {
  return '';
}

/**
 * AJAX callback for bind feed item to node.
 *
 * @param $feed_id
 *  The feed ID.
 * @param $vsite_id
 *  The vsite ID.
 * @param string $ajax
 */
function os_reader_ajax_copy_feed_to_news($feed_id, $vsite_id, $ajax = 'nojs') {
  $feed = os_reader_load($feed_id);
  $vsite = vsite_get_vsite($vsite_id);

  os_reader_copy_feed_to_news($feed, $vsite);

  if ($ajax == 'ajax') {
    $commands[] = ajax_command_html("#feed-{$feed_id}-{$vsite_id}", t('Copy to @vsite', array('@vsite' => $vsite->og->title)));
    $page = array('#type' => 'ajax', '#commands' => $commands);
    return $page;
  }
  else {
    drupal_goto('os-reader');
  }
}

/**
 * Implements hook_os_app_info().
 */
function os_reader_os_app_info() {
  $apps = array();

  $apps['os_reader'] = array(
    'path' => 'reader',
  	'nodetypes' => array(
  	  'feed',
    ),
    'views tabs' => array(
      'reader' => array('page'),
    ),
  );

  return $apps;
}

/**
 * Implements hook_vsite_og_node_type_info().
 */
function os_reader_vsite_og_node_type_info() {
  return array(
    'feed' => 'group content',
  );
}

/**
 * Implements hook_entity_info().
 */
function os_reader_entity_info() {
  return array(
    'os_feed_item' => array(
      'label' => t('OS feed item'),
      'entity class' => 'Entity',
      'base table' => 'os_feed_item',
      'fieldable' => TRUE,
      'controller class' => 'EntityAPIController',
      'entity keys' => array(
        'id' => 'id',
        'label' => 'title',
        'bundle' => 'type',
      ),
      'bundle keys' => array(
        'bundle' => 'type',
      ),
      'bundles' => array(
        'feed_item' => array(
          'label' => '',
          'admin' => array(
            'path' => 'admin/config/content/os_feed/manage/os_feed',
            'real path' => 'admin/config/content/os_feed/manage/os_feed',
            'access arguments' => array('os_feed manage'),
          ),
        ),
      ),
      'views controller class' => 'OsReaderViewsController',
      'metadata controller class' => 'OsReaderMetadataController',
    ),
  );
}

/**
 * Create an OS feed item object.
 *
 * @param $values
 *  The initialized values of the OS feed item object.
 *
 * @return Entity
 *  The entity object of the OS feed item entry.
 */
function os_reader_create($values = array()) {
  $values += array(
    'type' => 'feed_item',
    'created' => time(),
  );

  return entity_create('os_feed_item', $values);
}

/**
 * Load an OS feed item entry.
 *
 * @param $id
 *  The OS feed item identifier.
 *
 * @return Entity
 *  The OS feed item object.
 */
function os_reader_load($id) {
  $results = entity_load('os_feed_item', array($id));
  return reset($results);
}

/**
 * Load multiple OS feed item entries.
 *
 * @param $ids
 *  List of IDs to load.
 *
 * @return Entity
 *  List of OS feed item entries.
 */
function os_reader_load_multiple($ids) {
  return entity_load('os_feed_item', $ids);
}

/**
 * Delete multiple imported entities.
 *
 * @param $ids
 *  The identifiers of the imported entities.
 */
function os_reader_delete_multiple($ids) {
  entity_delete_multiple('os_feed_item', $ids);
}

/**
 * Implements hook_feeds_plugins().
 */
function os_reader_feeds_plugins() {
  $info = array();
  $info['OsFeedReaderFetcher'] = array(
    'name' => t('OS feed reader fetcher'),
    'description' => t('Fetch info from a out source.'),
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'OsFeedReaderFetcher',
      'file' => 'OsFeedReaderFetcher.inc',
      'path' => drupal_get_path('module', 'os_reader') . '/plugins',
    ),
  );
  return $info;
}

/**
 * Create a news node based on a feed item.
 *
 * @param $feed
 *  The feed object to copy.
 * @param $vsite
 *  VSITE object to which to assign the new node.
 */
function os_reader_copy_feed_to_news($feed, $vsite) {
  global $user;

  // Create the "News" node.
  $node = entity_create('node', array('type' => 'news'));
  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper->title->set($feed->title);
  $wrapper->body->value->set($feed->description);
  $wrapper->field_news_date->set($feed->created);
  $wrapper->field_photo->set(array('fid' => $feed->fid));

  $wrapper->{OG_AUDIENCE_FIELD}->set(array($vsite->id));
  $wrapper->author->set($user->uid);
  $wrapper->save();

  // Reference the feed to the node.
  $wrapper = entity_metadata_wrapper('os_feed_item', $feed);
  $wrapper->field_nodes_reference[] = $vsite->id;
  $wrapper->save();
}

/**
 * Return TRUE if feed item already copied to VSite.
 *
 * @param $feed_id
 *  The feed ID.
 * @param $vsite_id
 *  The VSite ID.
 *
 * @return
 *  Return TRUE if the feed item was already copied to the VSite, otherwise
 *  return FALSE.
 */
function os_reader_is_feed_item_copied_to_vsite($feed_id, $vsite_id) {
  $wrapper = entity_metadata_wrapper('os_feed_item', $feed_id);

  if (!$vsite_ids = $wrapper->field_nodes_reference->value(array('identifier' => TRUE))) {
    return;
  }

  return in_array($vsite_id, $vsite_ids);
}
