<?php
/**
 * @file
 * Code for the OS Booklets feature.
 */

include_once 'os_booklets.features.inc';

/**
 * hook os_widget
 *
 * Exposes blocks as OpenScholar widgets.
 */
function os_booklets_os_widget() {
  $items = array();
  
  // Displays "Archive" list of blog entry nodes by month
  $items['views-os_booklets-block'] = array(
      'module' => 'views',
      'delta' => 'os_booklets-block',
      'region' => 'sidebar_second',
      'weight' => '-10',
      'info' => 'Recent Documents'
  );
  
  return $items;
}