<?php

function os_wysiwyg_link_wysiwyg_include_directory($type) {
  switch ($type) {
    case 'plugins':
      return 'wysiwyg_plugins';
  }
}

function os_wysiwyg_link_get_media_browser_plugins() {
  return array();
}

function os_wysiwyg_link_get_media_browser_types() {
  return array();
}

function os_wysiwyg_link_menu() {
  $items = array();
  
  $items['os/wysiwyg/link/insert'] = array(
    'title' => 'Insert Link',
    'access arguments' => array('insert link into wysiwyg'),
    'page callback' => 'os_wysiwyg_link_insert',
    'file' => 'os_wysiwyg_link.insert.inc',
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function os_wysiwyg_link_permission() {
  $perms = array();
  
  $perms['insert link into wysiwyg'] = array(
    'title' => 'Insert a link into the Wysiwyg',
    'description' => 'Insert a link into the wysiwyg'
  );
  
  return $perms;
}

function os_wysiwyg_link_form_file_entity_add_upload_alter(&$form, &$form_state) {
  $args = $form_state['build_info']['args'][0];
  if (isset($args['no_redirect']) && $args['no_redirect']) {
    $form['#submit'][] = 'os_wysiwyg_link_add_upload_submit';
  }
}

function os_wysiwyg_link_add_upload_submit($form, &$form_state) {
  $form_state['no_redirect'] = true;
}

function os_wysiwyg_link_filter_info() { 
  $filters['owl_filter'] = array(
    'title' => t('Convert File links to correct path'),
    'description' => t('This filter will convert the paths of links to files to ensure they\'re always correct.'),
    'process callback' => 'os_wysiwyg_link_filter',
    'weight' => 1,
  );

  return $filters;
}

function os_wysiwyg_link_filter($text) {
  $matches = _os_wysiwyg_link_find_links($text);
  foreach ($matches as $m) {
    switch ($m[2]) {
      case 'fid':
        $file = file_load($m[3]);
        if (isset($file->uri)) {
          $link = str_replace($m[1], file_create_url($file->uri), $m[0]);
          $text = str_replace($m[0], $link, $text);
        }
        break;
      case 'url':
        if (url_is_external($m[3])) {
          $url = url($m[3], array('external' => TRUE));
        }
        else {
          $url = url($m[3], array('absolute' => TRUE));
        }
        $link = str_replace('href="'.$m[1], 'href="'.$url, $m[0]);
        $text = str_replace($m[0], $link, $text);
        break;
    }
  }
  return $text;
}

function _os_wysiwyg_link_find_links($str) {
  $matches = array();
  preg_match_all('~<a[^>]+href="([^"]+)"[^>]+data-(fid|url)="([^"]*)">[^<]*<\/a>~', $str, $matches, PREG_SET_ORDER);
  return $matches;
}
