<?php

function media_embed_menu() {
  $items['file/add/code'] = array(
    'title' => 'HTML',
    'description' => 'Add raw embed code to your media library.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_embed_add'),
    'access callback' => 'media_embed_access',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/media/media_embed'] = array(
    'title' => 'Embeded Code Domain Whitelist',
    'description' => 'Set the whitelist of allowed domains for iframes.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_embed_settings'),
    'file' => 'media_embed.admin.inc',
    'access arguments' => array('access administration pages'),
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function media_embed_ctools_plugin_api($module, $api) {
  if ($module == 'media' && $api == 'browser') {
    return array(
      'version' => 1,
    );
  }

  // required for browser previews and rendering of final file entity
  if ($module == 'file_entity' && $api == 'file_default_displays') {
    return array(
      'version' => 1,
    );
  }
}

/**
 * Implements hook_media_browser_plugin_info().
 */
function media_embed_media_browser_plugin_info() {
  $plugins = array();
  $plugins['media_embed'] = array(
    'title' => t('HTML'),
    'handler' => array(
      'path' => drupal_get_path('module', 'media_embed') . '/includes',
      'file' => 'MediaBrowserHTML.inc',
      'class' => 'MediaBrowserHTML',
    ),
    'access callback' => 'media_internet_access',
  );
  return $plugins;
}

/**
 * Access callback for the media_embed media browser plugin.
 */
function media_embed_access() {
  return user_access('administer media') || user_access('add media as raw html');
}

/**
 * Implement hook_permission().
 */
function media_embed_permission() {
  return array(
    'add media as raw html' => array(
      'title' => t('Add media as raw html'),
      'description' => t('Add media from remote sources such as other websites, YouTube, etc'),
    ),
  );
}

function media_embed_add($form, &$form_state = array(), $types = NULL) {
  $file = entity_create('file', array('type' => 'html'));
  $form['#file'] = $file;
  $form_state['file'] = $file;

  field_attach_form('file', $file, $form, $form_state);

  $white = media_embed_get_whitelist();
  if (count($white)) {
    $form['whitelist'] = array(
      '#markup' => t('You can add html with iframe, object, embed and script tags from the following sites:').'<br>'.implode(', ', $white),
    );
  }
  else {
    $form['whitelist'] = array(
      '#markup' => t('You may not add html with iframe, object, embed or script tags. Ask your site administrator to remedy this.'),
    );
  }
  $form['whitelist']['#weight'] = 4;

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#submit' => array('media_embed_add_submit'),
  );
  return $form;
}

/**
 * Implements hook_validate.
 * Ensures the HTML code given doesn't have any links to dangerous URLs
 * @param unknown_type $form
 * @param unknown_type $form_state
 */
function media_embed_add_validate($form, &$form_state) {
  $html = field_get_items('file', $form_state['file'], 'field_html_code');
  $html = trim($html[0]['value']);

  // Fields validation
  field_attach_form_validate('file', $form_state['file'], $form, $form_state);

  if (!media_embed_check_src($html)) {
    form_set_error('embed_code', 'This html contains an iframe, object, embed or script tag from an untrusted domain. If you believe this domain is safe, contact your site administrator.');
  }
}

function media_embed_add_submit($form, &$form_state) {
  $html = field_get_items('file', $form_state['file'], 'field_html_code');
  $html = trim($html[0]['value']);

  // create the new file entity
  $uri = 'embed://'.md5($html);
  $file = file_uri_to_object($uri);
  $titles = field_get_items('file', $form_state['file'], 'field_title');
  $file->filename = trim($titles[0]['value']);
  $file = entity_create('file', ((array)$file)+array('type' => 'html'));
 /* foreach ($form['#file'] as $key => $value) {
    if (!isset($file->$key)) {
      $file->$key = $value;
    }
  }*/
  $form['#file'] = &$file;
  $form_state['file'] = &$file;

  // save the fields and entity
  field_attach_submit('file', $file, $form, $form_state);
  $file = file_save($file);
}

function media_embed_check_src($html) {
  return TRUE;  // testing of submission
}

/**
 * Returns an array of all allowed domains
 * Invokes hook_media_embed_whitelist
 */
function media_embed_get_whitelist() {
  $domains = module_invoke_all('media_embed_whitelist');

  $domains = array_merge($domains, variable_get('media_embed_whitelist', array()));
  return $domains;
}

/**
 *  Create stream wrapper for oEmbed videos.
 */
function media_embed_stream_wrappers() {
  return array(
    'embed' => array(
      'name' => t('Embedded HTML'),
      'class' => 'MediaEmbedStreamWrapper',
      'description' => t('HTML provided by user.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}



/**
 * Implements hook_file_formatter_info().
 */
function media_embed_file_formatter_info() {
  $formatters['media_embed'] = array(
    'label' => t('Embedded HTML'),
    'default settings' => array('width' => '560', 'height' => '340'),
    'view callback' => 'media_embed_file_formatter_media_embed_view',
    'settings callback' => 'media_embed_file_formatter_media_embed_settings',
  );
  $formatters['media_embed_thumbnail'] = array(
    'label' => t('Embedded HTML Thumbnail'),
    'default settings' => array('width' => '560', 'height' => '340'),
    'view callback' => 'media_embed_file_formatter_media_embed_thumbnail_view',
    'settings callback' => 'media_embed_file_formatter_media_embed_thumbnail_settings',
  );
  return $formatters;
}

/**
 * Implements hook_file_default_displays().
 *
 * Provides default display configurations for media types.
 *
 * @see file_entity_schema()
 */
function media_embed_file_default_displays() {
  $default_displays = array();

  $default_styles = array();
  foreach(media_type_get_types() as $name => $type) {
    // For default and Large view modes, use the default width and height from
    // hook_file_formatter_info().
    $default_styles[$name . '__default__media_embed'] = array();
    $default_styles[$name . '__default__media_embed_thumbnail'] = array();

    // For the Preview view mode, match the width and height of the square
    // thumbnail in media_image_default_styles().
    $default_styles[$name . '__media_preview__media_embed_thumbnail'] = array('width' => '180', 'height' => '180');

    // For the Original view mode, set width and height to empty, so that they
    // use what's returned by the oEmbed response.
    $default_styles[$name . '__media_original__media_embed'] = array('width' => '', 'height' => '');
    $default_styles[$name . '__media_original__media_embed_thumbnail'] = array('width' => '', 'height' => '');
  }

  foreach ($default_styles as $display_name => $settings) {
    $default_displays[$display_name] = (object) array(
      'api_version' => 1,
      'name' => $display_name,
      'status' => 1,
      'weight' => 0,
      'settings' => $settings,
    );
  }

  return $default_displays;
}

/**
 * Implements hook_file_formatter_FORMATTER_view().
 */
function media_embed_file_formatter_media_embed_view($file, $display, $langcode) {
  $scheme = file_uri_scheme($file->uri);
  if ($scheme == 'embed') {
    $display['module'] = 'media_embed'; // prevents notice

    // Not a WYSIWYG editor instance.
    if (empty($file->override['wysiwyg'])) {
      field_attach_prepare_view('file', array($file->fid => $file), $display);
      entity_prepare_view('file', array($file->fid => $file));

      return field_attach_view('file', $file, $display);

      // pull the html from our table
      /*$result = db_select('media_embed', 'me')->fields('me', array('html'))->condition('fid', $file->fid)->execute();
      $html = $result->fetchAssoc();
      $html = $html['html'];
      $element = array(
        '#markup' => $html,
      );*/
    }

    // WYSIWYG will not handle iframes and the like properly. Just send back a placeholder image
    else {
      return array();
    }
  }
}