;
; Holds the modules that should be installed for multi-tenant sites
;

dependencies[] = entityreference
dependencies[] = purl
dependencies[] = spaces
dependencies[] = spaces_og
dependencies[] = og_views
dependencies[] = vsite
dependencies[] = vsite_domain
dependencies[] = vsite_menu
dependencies[] = vsite_layout
dependencies[] = vsite_register
dependencies[] = vsite_access
dependencies[] = vsite_vocab
dependencies[] = og
dependencies[] = os_subsites
dependencies[] = views_og_cache

;Depends on og/vsite
dependencies[] = os_activity