<?php 

/**
 * Implements hook_menu
 */
function harvard_menu() {
  $items['acquia_backups'] = array(
    'title' => 'Backups',
    'page callback' => 'harvard_acquia_backups_page',
    'file' => 'harvard.pages.inc',
    'file path' => drupal_get_path('module', 'harvard'),
    'access callback' => 'harvard_acquia_backups_page_access',
    'type' => MENU_CALLBACK,
  );

  $items['acquia_backups/%'] = $items['acquia_backups'];
  $items['acquia_backups/%']['page arguments'] = array(1);

  return $items;
}


/**
 * @function harvard_acquia_backups_page_access
 * 
 * Access check for acquia backup page
 */
function harvard_acquia_backups_page_access() {
  global $user;
  $users = variable_get('harvard_acquia_backups_whitelist', ''); //comma separated list of user names
  return (isset($user->name) && in_array($user->name, explode(',', $users)));
}
