<?php

/**
 * Implements hook_os_menu_tree_alter().
 */
function vsite_menu_os_menu_tree_alter($menu_key, &$tree) {
	
	
	
}





/**
 * Controller Plugin Hooks
 */

/**
 * Implements hook_spaces_plugins().
 */
function vsite_menu_spaces_plugins() {
  $plugins = array();
  $plugins['spaces_controller_menus'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'vsite_menu') . '/plugins',
      'file' => 'spaces_controller_menus.inc',
      'class' => 'spaces_controller_menus',
      'parent' => 'spaces_controler',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_spaces_registry().
 */
function vsite_menu_spaces_registry() {
  return array(
    'controllers' => array(
      'boxes' => array(
        'title' => t('Menus'),
        'plugin' => 'spaces_controller_menus',
      ),
    ),
  );
}