<?php

include_once('vsite_widgets.features.inc');

/**
 * hook block
 */
function vsite_widgets_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {

    $blocks[2]['info'] = t('ShareThis Button - Allows you to share posts using popular online services');
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 2:
      	return vsite_widgets_addthis();
      case 6:
      	return vsite_widget_rss();
    }
  }
}

/**
 * RSS block
 */
function vsite_widget_rss(){
  if (! $vsite = vsite_get_vsite()) {
    return;
  }

  if ($image = theme('image', 'misc/feed.png', t('Syndicate content'), 'RSS')) {
    $block['content'] = l($image, 'feed', array('html' => TRUE, 'attributes' => array('class' => 'feed-icon')));
  }

  return $block;

}



/**
 * Adds the addthis social networking link
 * @return array
 */
function vsite_widgets_addthis(){
  if (! module_exists('addthis')) {
    return;
  }

  $addthis_widget_type = variable_get('addthis_widget_type', 'addthis_button');
  $block['subject'] = t(''); //t('AddThis');
  $block['content'] = theme($addthis_widget_type);
  return $block;

}

function vsite_widgets_vsite_widgets(){

	return array(

    'vsite_widgets-4' => array(
      'module' => 'vsite_widgets',
      'delta' => '2',
      'weight' => 300,
      'region' => false,
      'label' => 'AddThis Button - Share posts using popular services',
    ),

   'vsite_widgets-6' => array(
      'module' => 'vsite_widgets',
      'delta' => '6',
      'weight' => -5,
      'region' => false,
      'label' => 'RSS feed',
      'cache' => BLOCK_CACHE_CONTENT_CACHE,
      'cache_keys' => array(
        'os_og' => array('current' => 'current'),
      ),
    ),

  );

}
