<?php
// $Id$

/**
 * @file
 * Hides read more links if a node has a body field that is not trimmed.
 *
 * Mimics Drupal 6 teaser "read more" link behavior: if a node's body is being
 * rendered shorter than the entire length, then display a "read more" link to
 * the full node view.
 *
 * In Drupal 7, in part because body is now just a field like everything else,
 * node teasers will always display read more links, even if they would display
 * a shorter (trimmed or summarized) body.
 */

/**
 * Implements hook_process_HOOK() for node.tpl.php.
 */
function body_readmore_process_node(&$vars) {
  // Only proceeds if we have a body and a "Read more" link in the first place.
  if (!isset($vars['content']['body']['#items'][0]['value']) || !isset($vars['content']['body'][0]['#markup'])) {
    return;
  }
  if (!isset($vars['content']['links']['node']['#links']['node-readmore'])) {
    return;
  }
  // Compares what will be displayed to the user against the full body value.
  $body_full      = trim($vars['content']['body']['#items'][0]['value']);
  $body_display   = trim($vars['content']['body'][0]['#markup']);
  $body_shortened = (bool)(strlen($body_full) > strlen($body_display));
  // Exits now if the body will be displayed shortened, this means there is
  // more body content to read by clicking "Read more", so we display the link.
  if ($body_shortened) {
    return;
  }
  // Otherwise, hides the "Read more" link by removing it from the render array.
  unset($vars['content']['links']['node']['#links']['node-readmore']);
}

