<?php

/**
 * @file
 * Code for OS Virtual Site: Presets
 */

/**
 * Implements hook_og_tasks_info().
 */
function vsite_preset_og_tasks_info($entity_type, $entity) {
  $tasks = array();
  $path = drupal_get_path('module', 'vsite_preset');
  // @fixme we should be able to load this via files[]  array in vsite_preset.info
  include_once($path . '/includes/vsite_task.inc');

  // Provides all simple section tasks.
  $sections = array('About', 'Academics', 'Activities', 'Overview', 'Research', 'Resources', 'Services');
  foreach ($sections as $title) {
    $key = 'vsite_preset_section_' . strtolower($title);
    $tasks[$key] = _vsite_preset_new_section_task($title);
  }

  // Provides task for 'News & Events'.
  $task = array(
    'title' => t('News & Events Section'),
    'description' => t('Sets up a standard News & Events site section.'),
    'required' => TRUE,
    'callback' => '_vsite_preset_section_newsevents_task',
    'file' => $path . '/includes/menu.inc',
  );
  $tasks['vsite_preset_section_newsevents'] = new vsite_task($task);

  // Provides task for 'HOME'.
  $task = array(
    'title' => t('HOME Section'),
    'description' => t('Sets up standard template for a HOME section.'),
    'required' => TRUE,
    'callback' => '_vsite_preset_section_home_task',
    'file' => $path . '/includes/menu.inc',
  );
  $tasks['vsite_preset_section_home'] = new vsite_task($task);

  return $tasks;
}

/**
 * Builds a new task that creates a page section and primary menu item.
 *
 * @param string $title
 *   The string to use for the page title and menu link title.
 * @return object $task
 *   The new vsite_task object to create the new page and new menu link.
 */
function _vsite_preset_new_section_task($title) {
  $path = drupal_get_path('module', 'vsite_preset');
  $replacements = array('@title' => $title);
  $properties = array(
    'title' => t('@title Section', $replacements),
    'description' => t('Sets up standard template for a @title section.', $replacements),
    'required' => TRUE,
    'callback' => '_vsite_preset_section_task',
    'arguments' => array('title' => t($title)),
    'file' => $path . '/includes/menu.inc',
  );
  $task = new vsite_task($properties);

  return $task;
}
