<?php
/**
 * @file
 * Code for the os_publications feature.
 */

include_once 'os_publications.features.inc';

function os_publications_query_biblio_alter(QueryAlterableInterface $query) {
  $space = spaces_get_space();
  if (module_exists('spaces') && $space->type == 'og') {
    $query->innerJoin('og_membership', 'ogm', 'n.nid = ogm.etid');
    $query->condition('ogm.entity_type', 'node');
    $query->condition('ogm.gid', $space->id);
  }
}
