<?php
/**
 * The "Teaser" View
 * Should just display the citation and book cover if there is one
 * @param unknown_type $vars
 */
function theme_os_publications_entry(&$vars) {

}

/**
 * Full Node View
 * Displays the citation in a field that can be clicked to select all of it
 * Also displays abstract, full text and notes if enabled.
 * @param unknown_type $vars
 */
function theme_os_publications_tabular(&$vars) {

}