<?php

/**
 * @file
 * Main module file for the imported entity.
 */

/**
 * Implements hook_entity_info().
 */
function imported_entity_entity_info() {
  return array(
    'imported_entity' => array(
      'label' => t('Imported entity'),
      'entity class' => 'Entity',
      'base table' => 'imported_entity',
      'controller class' => 'EntityAPIController',
      'entity keys' => array(
        'id' => 'id',
        'label' => 'title',
        'bundle' => 'type',
      ),
    ),
  );
}

/**
 * Create an imported entity object.
 *
 * @param $values
 *  The initialized values of the imported entity object.
 *
 * @return Entity
 *  The entity object of the imported entity entry.
 */
function imported_entity_create($values = array()) {
  global $user;

  $values += array(
    'time' => time(),
    'uid' => $user->uid,
  );

  return entity_create('imported_entity', $values);
}

/**
 * Load an imported entity entry.
 *
 * @param $id
 *  The imported entity identifier.
 *
 * @return Entity
 *  The imported entity object.
 */
function imported_entity_load($id) {
  $results = entity_load('imported_entity', array($id));
  return reset($results);
}

/**
 * Load multiple imported entity entries.
 *
 * @param $ids
 *  List of IDs to load.
 *
 * @return Entity
 *  List of imported entity entries.
 */
function imported_entity_load_multiple($ids) {
  return entity_load('imported_entity', $ids);
}

/**
 * Delete multiple imported entities.
 *
 * @param $ids
 *  The identifiers of the imported entities.
 */
function imported_entity_delete_multiple($ids) {
  entity_delete_multiple('imported_entity', $ids);
}

/**
 * Implements hook_feeds_plugins().
 */
function imported_entity_feeds_plugins() {
  $info = array();
  $info['ImportedEntityFetcher'] = array(
    'name' => t('Imported entity fetcher'),
    'description' => t('Fetch info from a out source.'),
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'ImportedEntityFetcher',
      'file' => 'importedEntityFetcher.inc',
      'path' => drupal_get_path('module', 'imported_entity') . '/plugins',
    ),
  );
  return $info;
}
