<?php

/**
 * @file
 * Core functionality for oEmbed
 */

/**
 * Implements hook_help().
 */
function oembedcore_help($path, $arg) {
  switch ($path) {
    case 'admin/help#oembedcore':
      $output = '<p>'. t('oEmbed module will allow your Drupal site to embed content from <a href="@oembed">oEmbed</a>-providers as well as for the site to become an oEmbed-provider itself so that other oEmbed-enabled websites can easily embed your content.', array('@oembed' => 'http://www.oembed.com/')) .'</p>';
      $output .= '<p>'. t('Add or enable <a href="@provider">providers</a> to embed content from other sites.', array('@provider' => url('admin/build/oembed/provider'))) .'</p>';
      return $output;
    case 'admin/build/oembed':
    case 'admin/build/oembed/provider':
      $output = '<p>'. t('Providers are other web sites with oEmbed endpoints whose content you can embed on your site.') .'</p>';
      return $output;
  }
}

/**
 * Implements hook_permission().
 */
function oembedcore_permission() {
  return array(
    'administer oembed' => array(
      'title' => t('Administer oEmbed'),
      'description' => t('Define providers for oEmbed.'),
    ),
  );
}

/**
 * Implements hook_flush_caches().
 */
function oembedcore_flush_caches() {
  // Because some oEmbed providers (e.g., http://embed.ly) charge per request,
  // allow cache_oembed to opt out of drupal_flush_all_caches() clearing.
  if (variable_get('oembed_cache_flush', TRUE)) {
    return array('cache_oembed');
  }
}

/**
 * Implements hook_cron().
 */
function oembedcore_cron() {
  // If cache_oembed opts out of oembedcore_flush_caches(), then system_cron()
  // doesn't clear its expired records, so do so here.
  if (!variable_get('oembed_cache_flush', TRUE)) {
    cache_clear_all(NULL, 'cache_oembed');
  }
}

/**
 * Implements hook_menu().
 */
function oembedcore_menu() {
  $items = array();

  $items['admin/config/media/oembed/settings'] = array(
    'title' => 'Settings',
    'description' => 'Settings for oEmbed',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oembedcore_settings'),
    'file' => 'oembedcore.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/config/media/oembed/test'] = array(
    'title' => 'Test',
    'description' => 'Test URLs for oEmbed',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oembedcore_test'),
    'file' => 'oembedcore.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 *
 * Instead of rewriting ctools export UI's hook_menu implementations, alter
 * the callback items to have a common menu item.
 */
function oembedcore_menu_alter(&$items) {

  // Create a new menu item where all oembed export UIs will be local tasks by
  // copying the export UI's menu item that will become the default local task.
  $items['admin/config/media/oembed'] = $items['admin/config/media/oembed/provider'];
  $items['admin/config/media/oembed']['title'] = 'oEmbed';
  $items['admin/config/media/oembed']['description'] = 'Admin overview of oEmbed.';

  $items['admin/config/media/oembed/provider']['type'] = MENU_DEFAULT_LOCAL_TASK;
}

/**
 * Implements of hook_theme().
 */
function oembedcore_theme() {
  $path = drupal_get_path('module', 'oembedcore') . '/theme';
  return array(
    'oembed' => array(
      'file' => 'oembedcore_theme.inc',
      'path' => $path,
      'variables' => array('embed' => NULL, 'title' => '', 'content' => ''),
    ),
  );
}

/**
 * Returns the provider for a url.
 *
 * @param string $url
 *  Teh url to get the provider for.
 * @return mixed
 *  A valid callback or FALSE
 */
function oembedcore_get_provider($url, &$matches) {
  $providers = oembedcore_providers();
  foreach ($providers as $regex => $info) {
    if (preg_match($regex, $url, $matches)) {
      if (!is_array($info)) {
        return (array) oembedcore_provider_load($info);
      }
      return $info;
    }
  }
  return FALSE;
}

/**
 * Returns all the registered providers, or the providers for a specific host.
 *
 * @param string $host
 *  Optional. Supply a hostname if you only want the provider patterns for a specific host.
 * @return array
 *
 * @todo Make this more like drupal_match_path()
 */
function oembedcore_providers() {
  $providers = &drupal_static(__FUNCTION__, array());

  if (!$providers) {
    $cache_key = 'oembedcore:providers';

    if (($cache = cache_get($cache_key)) && isset($cache->data)) {
      $providers = $cache->data;
    }
    else {
      $providers = array();

      // oEmbed providers are local services that return content over callback
      // function.
      $modules = module_implements('oembedprovider');
      foreach ($modules as $module) {
        $ps = call_user_func($module . '_oembedprovider');
        foreach ($ps as $pattern => $info) {
          $patterns = array();
          $patterns[] = str_replace('\*', '.*', preg_quote($pattern, '#'));
          if (!empty($patterns)) {
            $regex_pattern = '#'. implode('|', $patterns) .'#i';
            $providers[$regex_pattern] = $info;
          }
        }
      }

      // oEmbed provider definitions are remote web services.
      $provider_definitions = oembedcore_provider_load_all();
      foreach ($provider_definitions as $provider_definition) {
        if (empty($provider_definition->disabled)) {
          $patterns = array();
          $schemes = array_filter(preg_split("/(\r\n?|\n)/", $provider_definition->scheme));
          foreach ($schemes as $scheme) {
            $patterns[] = str_replace('\*', '.*', preg_quote($scheme, '#'));
          }
          if (!empty($patterns)) {
            $regex_pattern = '#'. implode('|', $patterns) .'#i';
            $providers[$regex_pattern] = $provider_definition->name;
          }
        }
      }
      uksort($providers, '_oembedcore_specificity_compare');
      drupal_alter('oembedprovider', $providers);
      cache_set($cache_key, $providers);
    }
  }

  return $providers;
}

/**
 * Helper function that compares the length of match expressions.
 */
function _oembedcore_specificity_compare($a, $b) {
  return strlen($a) - strlen($b);
}

/**
 * Reset the registered provider caches.
 */
function oembedcore_providers_reset() {
  drupal_static_reset('oembedcore_providers');
  cache_clear_all('oembedcore:providers', 'cache');
}

/**
 * Fetch data for an embeddable URL.
 *
 * @param string $url
 *   An external URL for the content to embed.
 * @param array $attributes
 *   An associative array of attributes, with the following keys:
 *   - 'maxwidth'
 *       The maximum width of the embed, in pixels.
 *   - 'maxheight'
 *       The maximum height of the embed, in pixels.
 * @return
 *   False or an object representing the embeddable data of the URL.
 */
function oembedcore_oembed_data($url, $attributes = array()) {
  $matches = array();
  $attributes = array_filter($attributes);
  if ($provider = oembedcore_get_provider($url, $matches)) {
    drupal_alter('oembed_request', $attributes, $provider, $url);
    return oembedcore_oembed_fetch($provider, $url, $matches, $attributes);
  }
  return FALSE;
}

/**
 * oEmbed fetcher and parser.
 *
 * This handles fetching from remote providers and local registered callbacks.
 * It does not cache the responses because they are cached when rendered.
 */
function oembedcore_oembed_fetch($provider, $url, $matches, $attributes = array()) {
  $embed = FALSE;

  // Mock a render element for cache keys and expiration. This element will
  // not be rendered.
  $element = oembedcore_render_cache('oembed_request', $url, $attributes);
  $cache_key = implode(':', $element['#cache']['keys']);
  $cache = cache_get($cache_key, $element['#cache']['bin']);

  // Cache hit.
  if ($cache && isset($cache->data)) {
    $embed = $cache->data;
  }
  else {
    // Cache miss.

    // Drupal oEmbed provider uses function callbacks for internal requests.
    if (!empty($provider['callback'])) {
      $embed = call_user_func($provider['callback'], $provider, $url, $matches, $attributes);
      if ($embed) {
        $embed = $embed;
      }
    }
    else {

      // Remote oEmbed endpoint request.
      $attributes['url'] = $url;
      $query = http_build_query($attributes, NULL, '&');
      $fetch_url = $provider['endpoint'] . '?' . $query;

      //TODO: Add alternative ways of fetching the content - like http client?
      $response = drupal_http_request($fetch_url);
      if (!isset($response->error)) {
        $embed = json_decode($response->data, TRUE);
        if (!is_array($embed)) {
          try {
            $xml = @new SimpleXMLElement($response->data);
            $embed = array();
            foreach ($xml as $key => $value) {
              $embed[$key] = (string) $value;
            }
          }
          catch (Exception $e) {
            watchdog('oembed', 'Could not parse response from %url.', array('%url' => $fetch_url), WATCHDOG_ERROR);
          }
        }

        if (empty($embed['version']) || empty($embed['type']) || intval($embed['version']) != 1) {
          $embed = FALSE;
        }

        if ($embed && !isset($embed['title'])) {
          $embed['title'] = '';
        }

        if (!$embed) {
          watchdog('oembed', 'Response from %url not a valid oEmbed response.', array('%url' => $fetch_url), WATCHDOG_ERROR);
        }
      }
      else {
        watchdog('oembed', 'Error fetching data from %url.', array('%url' => $fetch_url), WATCHDOG_ERROR);
      }
    }

    if ($embed) {
      cache_set($cache_key, $embed, $element['#cache']['bin'], $element['#cache']['expire']);
    }
  }

  // Decorate the oEmbed response object with additional properties that are
  // handy when theming the output.
  if ($embed) {
    $embed['original_url'] = $url;
    $embed['provider'] = $provider['name'];
    $embed['provider_subtype'] = isset($provider['subtype']) ? $provider['subtype'] : $provider['name'];
  }

  return $embed;
}

/**
 * Implements hook_element_info().
 */
function oembedcore_element_info() {

  // Standard oEmbed that changes its theme based on response.
  $types['oembed'] = array(
    '#theme' => 'oembed',
    '#embed' => NULL,
    '#attributes' => array(),
    '#pre_render' => array(
      'oembedcore_pre_render_fetch',
      'oembedcore_pre_render_retheme',
      'oembedcore_pre_render_content',
    ),
  );

  // Retrieves an image (photo or thumbnail) or nothing.
  $types['oembed_thumbnail'] = array(
    '#theme' => 'oembed',
    '#embed' => NULL,
    '#attributes' => array(),
    '#pre_render' => array(
      'oembedcore_pre_render_fetch',
      'oembedcore_pre_render_thumbnail',
      'oembedcore_pre_render_content',
    ),
  );

  // Retrieves an image (photo or thumbnail) or nothing.
  $types['oembed_wysiwyg'] = array(
    '#theme' => 'image',
    '#embed' => NULL,
    '#attributes' => array(),
    '#pre_render' => array(
      'oembedcore_pre_render_fetch',
      'oembedcore_pre_render_thumbnail',
      'oembedcore_pre_render_image',
    ),
  );

  return $types;
}

/**
 * Change oEmbed request into a thumbnail.
 *
 * This is here for Media module WYSIWYG support. When a video or image is added
 * to a text area, this step makes sure the WYSIWYG receives an image to stand
 * in for the real media. It must be an actual img element.
 */
function oembedcore_pre_render_thumbnail($element) {

  // Only act when the oEmbed response is true.
  if (!empty($element['#printed'])) {
    return $element;
  }

  $embed = $element['#embed'];

  // Check if the oEmbed response provides a thumbnail image.
  if (empty($embed['url']) && empty($embed['thumbnail_url'])) {
    $element['#printed'] = TRUE;
    return $element;
  }
  // If there's no URL for an image, don't render anything.
  else if (empty($embed['url'])) {
    $element['#embed']['url'] = $embed['thumbnail_url'];
    $element['#embed']['width'] = $embed['thumbnail_width'];
    $element['#embed']['height'] = $embed['thumbnail_height'];
    $element['#embed']['type'] = 'photo';
  }

  return $element;
}

/**
 * Converts oEmbed response to a plain image.
 */
function oembedcore_pre_render_image($element) {
  // Only act when the oEmbed response is true.
  if (!empty($element['#printed'])) {
    return $element;
  }

  $embed = $element['#embed'];

  if (!empty($element['#display_options'])) {
    $element['#display_options'] += array('width' => NULL, 'height' => NULL);
    image_dimensions_scale($embed, $element['#display_options']['width'],  $element['#display_options']['height']);
  }

  $element['#path'] = $embed['url'];
  $element['#width'] = $embed['width'];
  $element['#height'] = $embed['height'];

  return $element;
}

/**
 * Populate variables expected in oEmbed theme function.
 */
function oembedcore_pre_render_content($element) {

  // Only act when the oEmbed response is true.
  if (!empty($element['#printed'])) {
    return $element;
  }

  $embed = $element['#embed'];

  if (!empty($embed['title'])) {
    $element['#title'] = array(
      '#markup' => $embed['title'],
    );
  }

  switch ($embed['type']) {
    case 'photo':
      if (!empty($element['#display_options'])) {
        $element['#display_options'] += array('width' => NULL, 'height' => NULL);
        image_dimensions_scale($embed, $element['#display_options']['width'], $element['#display_options']['height']);
      }
      $element['#content'] = array(
        '#theme' => 'image',
        '#path' => $embed['url'],
        '#alt' => oembedcore_alt_attr($embed),
        '#attributes' => $element['#attributes'],
        '#width' => $embed['width'],
        '#height' => $embed['height'],
      );
      break;

    case 'link':
      // `link` type responses allow a provider to return any generic embed data. To
      // support specific providers' use of this type, create a specific theme function
      // for the provider, e.g. theme('oembed__link__posterous').
      $element['#content'] = array(
        '#theme' => 'link',
        '#path' => $embed['original_url'],

        // oembedcore_alt_attr() returns output from t() and is sanitized.
        '#text' => empty($embed['title']) ? oembedcore_alt_attr($embed) : check_plain($embed['title']),
        '#options' => array(
          'absolute' => TRUE,
          'attributes' => array('class' => 'oembed-link'),
          'html' => TRUE,
        ),
      );
      break;

    case 'video':
    case 'rich':
      // This would be the place to filter embedded HTML.
      $element['#content'] = array(
        '#markup' => $embed['html'],
      );
      break;
  }

  return $element;
}

/**
 * Rewrite the theme parameter based on the response.
 */
function oembedcore_pre_render_retheme($element) {

  // Only act when the oEmbed response is true.
  if (!empty($element['#printed'])) {
    return $element;
  }

  $embed = $element['#embed'];
  $element['#theme'] = 'oembed__'. $embed['type'] .'__'. $embed['provider'] .'__'. $embed['provider_subtype'];
  return $element;
}

/**
 * Pre render fetches the oEmbed data.
 */
function oembedcore_pre_render_fetch($element) {
  $embed = oembedcore_oembed_data($element['#url'], $element['#request_options']);

  // Prevent rendering if the response is bad.
  if (!$embed) {
    $element['#printed'] = TRUE;
    return $element;
  }

  $element['#embed'] = $embed;

  // Recalculate cache expire time based on response.
  if (isset($embed['cache_age']) && $element['#cache']['expire'] != CACHE_PERMANENT) {
    $expire = REQUEST_TIME + intval($embed['cache_age']);
    if ($expire > $element['#cache']['expire']) {
      $element['#cache']['expire'] = $expire;
    }
  }

  return $element;
}

/**
 * Prepare an element for caching based on a oEmbed request.
 *
 * @param $type
 *   Element type.
 * @param $url
 *   URL to embed.
 * @param $options
 *   oEmbed options.
 * @param $expire
 *   The cache expire time, passed eventually to cache_set().
 * @param $granularity
 *   One or more granularity constants passed to drupal_render_cid_parts().
 *
 * @return
 *   A renderable array with the following keys and values:
 *   - #type: The passed-in element $type.
 *   - #url: The passed-in $url.
 *   - #options: The passed-in $options.
 *   - #cache: An associative array prepared for drupal_render_cache_set().
 *
 * @see drupal_render_cache_by_query().
 */
function oembedcore_render_cache($type, $url, $request_options = array(), $display_options = array(), $expire = NULL, $granularity = NULL) {
  $cache_keys = array();
  $cache_keys[] = $type;
  $cache_keys[] = substr($url, -1) == '/' ? substr($url, 0, -1) : $url;
  if (!empty($request_options) || !empty($display_options)) {
    $cache_keys[] = hash('sha256', serialize($request_options + $display_options));
  }

  // If expire is not set, use default value and adjust for request time.
  if (!isset($expire)) {
    $expire = variable_get('oembed_cache_lifetime', 3600);
    if ($expire) {
      $expire += REQUEST_TIME;
    }
  }

  return array(
    '#type' => $type,
    '#url' => $url,
    '#request_options' => $request_options,
    '#display_options' => $display_options,
    '#cache' => array(
      'keys' => $cache_keys,
      'granularity' => $granularity,
      'expire' => $expire,
      'bin' => 'cache_oembed',
    ),
  );
}

/**
 * Generate a string for use as ALT attribute.
 */
function oembedcore_alt_attr($embed) {

  // alt attribute using hopefully available title and provider name.
  if (!empty($embed['title'])) {
    $string = '@title';
  } else {
    $string = 'Embedded @type';
  }
  if ($embed['provider_name']) {
    $string .= ' on @provider_name';
  }

  return t($string, array('@title' => $embed['title'], '@type' => $embed['type'], '@provider_name' => $embed['provider_name']));
}

/**
 * Implement hook_ctools_plugin_directory().
 */
function oembedcore_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'export_ui') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function oembedcore_ctools_plugin_api($module, $api) {
  if ($module == 'oembedcore' && $api == 'oembed_provider') {
    return array('version' => 1);
  }
}

// --------------------------------------------------------------------------
// Preset database info.

/**
 * Load a single provider.
 */
function oembedcore_provider_load($name) {
  ctools_include('export');
  $result = ctools_export_load_object('oembedcore_provider', 'names', array($name));
  if (isset($result[$name])) {
    return $result[$name];
  }
  else {
    return FALSE;
  }
}

/**
 * Load all providers.
 */
function oembedcore_provider_load_all() {
  ctools_include('export');
  return ctools_export_load_object('oembedcore_provider');
}

/**
 * Implement hook_preprocess_file_entity().
 */
function oembedcore_preprocess_file_entity(&$vars, $hook) {
  $scheme = file_uri_scheme($vars['uri']);
  if ($scheme == 'oembed') {
    $wrapper = file_stream_wrapper_get_instance_by_uri($vars['uri']);
    if ($embed = oembedcore_oembed_data($wrapper->interpolateUrl())) {
      $vars['oembed_response'] = $embed;
      $vars['classes_array'][] = 'oembed-'. $embed['type'];
      $vars['classes_array'][] = 'oembed-'. $embed['provider'];
    }
    $vars['title_attributes_array']['class'][] = 'oembed-title';

    // This conflicts with default file_entity.tpl.php which hardcodes a class attribute.
    $vars['content_attributes_array']['class'][] = 'oembed-content';
  }
}
