<?php
// $Id$

/**
 * @file
 * Code for the os_publications feature.
 */

include_once 'os_publications.features.inc';

/**
 * Implements hook_os_app_info().
 */
function os_publications_os_app_info() {
  $apps = array();

  $apps['os_publications'] = array(
    'path' => 'publications',
  	'nodetypes' => array(
  	  'biblio',
    ),
  );

  return $apps;
}


/**
 * Implements hook_biblio_fields_info().
 */
function os_publications_biblio_fields_info() {
  // URL title.
  $items['biblio_url_title'] = array(
    'description' => 'Biblio URL title',
    'field' => array(
      'cardinality' => '1',
      'field_name' => 'biblio_url_title',
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
      ),
      'type' => 'text',
    ),
    'instance' => array(
      'label' => 'Biblio URL title',
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '-3',
      ),
    ),
  );

  return $items;
}

/**
 * Implements hook_os_add_new_links_alter().
 */
function os_publications_os_add_new_links_alter(&$links) {
  if (!in_array($_GET['q'], array('publications'))) {
    return;
  }

  $links['add_publication'] = array(
    'title' => t('publication'),
    'href' => 'biblio/add',
  );
}
