<?php
// $Id$

/**
 * @file
 * Customizations for Gary King's website.
 */

/**
 * Implements hook_init().
 */
function gary_init() {
  drupal_add_library('system', 'ui.tabs');
}

/**
 * Implements hook_menu().
 */
function gary_menu() {
  $items = array();

  $items['iqss_gary_research_group'] = array(
    'title' => 'Research Group',
    'page callback' => 'gary_people_page',
    'access arguments' => array('access content'),
    'file' => 'gary.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Returns TRUE if the purl of the active vsite is "gary".
 */
function _gary_is_gary() {
  $vsite = vsite_get_vsite();
  return ($vsite && $vsite->group->purl == 'gking');
}

