<?php 

/**
 * Implements hook_install().
 */
function vsite_vocab_install() {
  //Get the weight of og_vocab
  $weight = db_query("SELECT weight FROM {system} WHERE type = 'module' AND name = 'og_vocab' ")->fetchField();
  $weight++;
  
  // Required to alter vocab forms after og_vocab
  db_update('system')
  ->fields(array('weight' => $weight))
  ->condition('type', 'module')
  ->condition('name', 'vsite_vocab')
  ->execute();
}