<?php

/**
 * Alter information returned from module/theme info files
 */
function vsite_vocab_system_info_alter(&$info, $file, $type){
  static $working;

  // Only alter the vsite_vocab info file
  if ($type != 'module' || $file->name != 'vsite_vocab' || $working) {
    return;
  }

  $working = true;

  // Add the feature settings for the dynamically managed og vocab reference fields
  if (! is_array($info['features']['field']))
    $info['features']['field'] = array();

  include_once ('vsite_vocab.features.field.inc');
  foreach ( vsite_vocab_get_vocab_fields() as $field => $definition ) {
    if (! in_array($field, $info['features']['field'])) {
      $info['features']['field'][] = $field;
    }
  }

  $working = false;
}