<?php
/**
 * Implementation of hook_menu
 */
function cp_settings_menu() {
  $items = array();

  $items['cp/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cp_settings_form'),
    'file' => 'cp_settings.form.inc',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'spaces_access_admin',
    'weight' => 30,
  );

  return $items;
}

/**
 * Gets all the settings a module could define for a site
 * but there aren't enough of to have its own page.
 */
function cp_settings_get_setting_forms() {
  $settings = module_invoke_all('cp_settings');
  drupal_alter('cp_settings', $settings);

  return $settings;
}