<?php
// $Id$

/**
 * Implements hook_help().
 */
function os_help_help($path, $arg) {
  /*
  switch ($path) {
    case 'cp/build':
    case 'cp/build/features':
      $topic = 'Features';
      break;
    case 'cp/build/layout':
      $topic = 'Customizing-Your-Site-Layout';
      break;
    case 'cp/appearance':
    case 'cp/appearance/theme':
      $topic = 'Theme-Selection';
      break;
    case 'cp/build/menus':
      $topic = 'Menus';
      break;
    case 'cp/build/taxonomy':
      $topic = 'Categorizing-Your-Content---Taxonomy';
      break;
    case 'cp/settings/site_info/%':
      $topic = 'Site-Information';
      break;
    case 'cp/settings':
    case 'cp/settings/generic':
      $topic = 'Site-Settings';
      break;
    case 'cp/content':
      $topic = 'Managing-Your-Content';
      break;
    case 'cp/content/files':
      $topic = 'Managing-Files-and-Images';
      break;
    case 'cp/users':
      $topic = 'Managing-Your-Users';
      break;
    case 'cp/news':
      $topic = 'Getting-Project-News';
      break;
    case 'cp/support':
      $topic = 'Getting-Support';
      break;
  }
  if (isset($topic)) {
    return theme('advanced_help_topic', array(
    	'module' => 'os_help',
    	'topic' => $topic
    ));
  }
  */
}

/**
 * Implements hook_form_alter().
 */
function os_help_form_alter(&$form, $form_state, $form_id) {
  // _os_help_traverse_form($form, $form_id);
  /* 2012-09-25 this code from OS2 looks broken. commenting out until qa
  if (isset($form['#description'])) {
    $form['#description'] =  _os_help_get_theme_variables('form', $form_id) . ' ' . $form['#description'];
  }
  else {
    $form['#description'] = _os_help_get_theme_variables('form', $form_id);
  }
  */
}

/**
 * Recursively traverses a form object as an array and adds help links.
 */
function _os_help_traverse_form(&$element, $form_id) {
  /*
  if (is_object($element)) {
    $element = (array)$element;
  }
  foreach (element_children($element) as $child) {
    _os_help_traverse_form($element[$child], $form_id . ':' . $child);
  }
  _os_help_attach_help_link($element, $form_id);
  */
}

/**
 * Form traversal callback; prepends elements with custom help link if found.
 *
 * @see _os_help_traverse_form().
 * @see os_help_form_alter().
 */
function _os_help_attach_help_link(&$element, $form_id) {
  /*
  // Ignores elements without a type value or with an excluded type.
  $ignore = array('button', 'image_button', 'submit', 'markup', 'token', 'hidden', 'form', 'value', 'weight');
  if (!isset($element['#type']) || in_array($element['#type'], $ignore)) {
    return;
  }

  $variables = _os_help_get_theme_variables($form_id);
  if (!$variables) {
    return;
  }

  $link = theme('advanced_help_topic', $variables);

  if ((string) $element['#type'] === 'fieldset') {
    // @todo use form ['#attached'] ?
    drupal_add_css(drupal_get_path('module', 'os_help') . '/os_help.css');
    $link = preg_replace('/class="(.+?)"/', 'class="\1 os_help-nofloat"', $link);
  }
  $element['#description'] = isset($element['#description']) ? $link . ' ' . $element['#description'] : $link;
  */
}

/**
 * Returns theme variables for a given OS Help topic ID, or FALSE if none found.
 */
function _os_help_get_theme_variables($id) {
  /*
  static $theme_variables = array(
    'spaces_features_form:spaces_features:scholar_announcements' => array('module' => 'os_help', 'topic' => 'Announcement-feature'),
    'spaces_features_form:spaces_features:scholar_biocv' => array('module' => 'os_help', 'topic' => 'Bio---CV-feature'),
    'spaces_features_form:spaces_features:scholar_blog' => array('module' => 'os_help', 'topic' => 'Blog-feature'),
    'spaces_features_form:spaces_features:scholar_book' => array('module' => 'os_help', 'topic' => 'Booklet-feature'),
    'spaces_features_form:spaces_features:scholar_classes' => array('module' => 'os_help', 'topic' => 'Class-feature'),
    'spaces_features_form:spaces_features:scholar_pages' => array('module' => 'os_help', 'topic' => 'Pages-feature'),
    'spaces_features_form:spaces_features:scholar_events' => array('module' => 'os_help', 'topic' => 'Events-feature'),
    'spaces_features_form:spaces_features:scholar_dvn' => array('module' => 'os_help', 'topic' => 'Dataverse-feature'),
    'spaces_features_form:spaces_features:scholar_feeds' => array('module' => 'os_help', 'topic' => 'Feed-feature'),
    'spaces_features_form:spaces_features:scholar_front' => array('module' => 'os_help', 'topic' => 'Front-feature'),
    'spaces_features_form:spaces_features:scholar_image_gallery' => array('module' => 'os_help', 'topic' => 'Image-Gallery-feature'),
    'spaces_features_form:spaces_features:scholar_links' => array('module' => 'os_help', 'topic' => 'Links-feature'),
    'spaces_features_form:spaces_features:scholar_profiles' => array('module' => 'os_help', 'topic' => 'Profiles-feature'),
    'spaces_features_form:spaces_features:scholar_publications' => array('module' => 'os_help', 'topic' => 'Publications-feature'),
    'spaces_features_form:spaces_features:scholar_presentations' => array('module' => 'os_help', 'topic' => 'Presentations-feature'),
    'spaces_features_form:spaces_features:scholar_reader' => array('module' => 'os_help', 'topic' => 'Reader-feature'),
    'spaces_features_form:spaces_features:scholar_software' => array('module' => 'os_help', 'topic' => 'Software-feature'),
    'vsite_layout_settings_form:page_type' => array('module' => 'os_help', 'topic' => 'Customizing-Your-Site-Layout'),
  );
  if (!isset($theme_variables[$id])) {
    return FALSE;
  }

  return $theme_variables[$id];
  */
}
