<?php

/**
 * Provides and CRUD functions needed for adding or removing users from your openscholar site
 *
 * @file luser.inc
 *
 * Provides layout management and crud functions
 *
 * os_layout_get
 *  Return an array of block settings for a single context
 *
 *
 */

/**
 * Returns the blocks for a individual context
 *
 * @param string $context
 * The identifier string for a context
 *
 * @param $load_meta
 * Add meta-data used by admin forms
 *
 * @param $unused_blocks
 * Add all unused site blocks
 *
 * @return array
 * List of blocks
 */
/**
 * Add a user, and if you are in a group add them to your group
 */
function os_user_add(){
  
  
  
}