<?php
/**
 * @file
 * Code for the os_dataverse feature.
 */

include_once 'os_dataverse.features.inc';

/**
 * Drupal hooks
 */

/**
 * Implements hook_menu().
 */
function os_dataverse_menu() {
  
  $items = array();
  $items['data'] = array(
    'title' => 'Data',
    'page callback' => '_os_dataverse_data_view',
    'access callback' => 'spaces_access_feature',
    'access arguments' => array('view', 'os_dataverse'),
    'menu_name' => 'features',
  );

 $items['features/os_dataverse'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os_dataverse_settings'),
    'access callback' => module_exists('spaces') ? 'spaces_access_admin' : 'user_access',
    'access arguments' => module_exists('spaces') ? array() : array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'os_dataverse.pages.inc',
  );
  
  return $items;
}

/**
 * Implements hook_preprocess_page().
 *
 * @param $vars
 */
function os_dataverse_preprocess_page(&$vars) {
  $active_menu = menu_get_item();
  if ($active_menu['path'] == 'data') {
    $vars['title'] = '';
  }
}

/**
 * OpenScholar hooks
 */

/**
 * Custom functions
 */
  
/**
 * Provides content for page at /data
 * 
 * @todo cleanup inline markup into theme hook
 */
function _os_dataverse_data_view() {
  drupal_add_js(drupal_get_path('module', 'os_dataverse') . '/os_dataverse.js');
  $vsite = vsite_get_vsite();
  $dvn_alias = variable_get('os_dataverse_dataverse_alias', '');

  if ($vsite && $dvn_alias) {
    // Embeds contents of Dataverse (DVN) hosted web page in an iframe
    $path = $dvn_alias;
    if(strlen($_REQUEST['dvn_subpage'])) $path .= "/".ltrim($_REQUEST['dvn_subpage'],"/");
    return "<div id=\"feature-dataverse\"><iframe name=\"res\" scrolling=\"auto\" src =\"" . $path . "\"></iframe></div>";
  }
  else if ($vsite && $vsite->access_admin()) {
    $l1 = l('feature', "cp/build/features");
    $l2 = l('http://dvn.iq.harvard.edu', 'http://dvn.iq.harvard.edu', array('absolute' => TRUE));
    $result = "<p>No dataverse alias was found. Please set up your dataverse alias in your \"scholar dvn\" " . $l1 . " settings </p>";
    $result .= "<p> If you don't have a dataverse, go to " . $l2 .  " to create your own dataverse to upload your data </p>";
    return $result;
  }
  else {
    return t('No dataverse available yet');
  }
}

/**
 * Throws error if dataverse URL does not begin with http://
 * 
 * @param unknown_type $element
 * @param unknown_type $form_state
 */
function _os_dataverse_alias_validate($element, &$form_state) {
  if (strpos($form_state['values']['scholar_dvn_dvn_alias'], 'http:') === FALSE) {
    form_set_error('os_dataverse_alias', t('Dataverse alias must begin with http://'));
  }
}