<?php
// $Id$


/**
 * @file
 * Code for the OS links feature.
 */

include_once ('os_links.features.inc');

/**
 * Drupal hooks
 */

/**
 * Implements hook_process_hook() for node.
 *
 * Removes the username from $submitted info on blog type nodes.
 */
function os_links_process_node(&$vars) {
  if ($vars['type'] !== 'link' || (int)$vars['teaser'] !== 1) return;

  // Changes the title URL destination from node alias to link field URL.
  $field_name = 'field_links_link';
  $items = field_get_items('node', $vars['node'], $field_name);
  $vars['node_url'] = $items[0]['url'];

  // Removes "read more" link from bottom of teaser display.
  if (isset($vars['content']['links']['node']['#links']['node-readmore'])) {
    unset($vars['content']['links']['node']['#links']['node-readmore']);
  }
}

/**
 * Implements hook_form_FORM_ID_form_alter() for link_node_form.
 */
function os_links_form_link_node_form_alter(&$form, &$form_state, $form_id) {
  $form['actions']['submit']['#submit'][] = '_os_links_form_redirect';
}

/**
 * OpenScholar hooks
 */

/**
 * Implements hook_vsite_og_node_type_info().
 */
function os_links_vsite_og_node_type_info() {
  return array(
    'link' => 'group content',
  );
}

/**
 * Custom functions
 */

/**
 * Redirects user to Links page, individual link nodes should not be viewed.
 */
function _os_links_form_redirect($form, &$form_state) {
  $form_state['redirect'] = 'links';
}

