<?php

/**
 * @file os_migrate.module
 *
 * Handles migration of openscholar from drupal6 to drupal7
 **/

/**
 * Implementation of hook_migrate_api
 *
 * Informs the Migrate module that this module provides migration classes
 */
function os_migrate_migrate_api() {
  return array('api' => 2);
}

/**
 * implementation of hook_mail_alter
 * 
 * for dev only, lets make sure all mails are sent to localhost
 **/
function os_migrate_mail_alter(&$mail) {
  $mail['to'] = 'root@localhost'; //just in case previous mail was badly formed
}

/*
 * bash: set vars to also disable mail...
echo user_mail_{register_{admin_created,no_approval_required,pending_approval},password_reset,status_{blocked,activated},cancel_confirm,status_canceled}_notify | xargs -n1 | while read var ; do drush @d7 vset -y $var '' ; done
*/

/**
 * Implementation of hook_menu
 **/
function os_migrate_menu() {
  $items['admin/config/os_migrate'] = array(
    'title' => 'OpenScholar Migration',
    'description' => 'OpenScholar Migration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os_migrate_admin'),
    'access arguments' => array('administer site configuration'),
    'file' => 'os_migrate.admin.inc',
  );

  return $items;
}

