<?php
/**
 * @file
 * Code for the Profiles feature.
 */

include_once 'os_profiles.features.inc';

/**
 * Implements hook_process_hook() for node.
 *
 * Enter description here...
 */
function os_profiles_process_node(&$vars) {
  if ($vars['type'] !== 'person') return;
  
  // Moves the profile photo thumbnail before teaser title (full name)
  $vars['title_prefix'] = $vars['content']['field_person_photo'];
  $vars['title_prefix']['#suffix'] = '<h1 id="page-title">' . $vars['title'] . '</h1>';
  $vars['title_prefix']['#attached'] = array(
  	'css' => array(
  		'type' => 'file',
  		'data' => drupal_get_path('module', 'os_profiles') . '/os_profiles.css',
  	),
  );
  unset($vars['content']['field_person_photo']);
  
  // Toggles header tag depending on view mode
  $h = ($vars['teaser']) ? '4' : '3';
  
  // Customizes field markup with prefixes and suffixes
  $title_plain = $vars['content']['field_professional_title'][0]['#markup'];
  $vars['content']['field_professional_title'][0]['#markup'] = '<h' . $h . '>' . $title_plain . '</h' . $h . '>';
  $email_plain = $vars['content']['field_email'][0]['#markup'];
  $vars['content']['field_email'][0]['#markup'] = '<a href="mailto:' . $email_plain . '">email</a>';
  $phone_plain = $vars['content']['field_phone'][0]['#markup'];
  $vars['content']['field_phone'][0]['#markup'] = '<em>p:</em> ' . $phone_plain;
}

/**
 * Implements hook_node_presave().
 * 
 * Generates node title for Person nodes
 */
function os_profiles_node_presave($node) {
  if ($node->type !== 'person') return;
  
  // Sets the node title like "[first] [middle] [last]"
  $title = _os_profiles_person_node_title($node);
  if ($title) $node->title = $title;
}

/**
 * Prepares the node title for person nodes.
 */
function _os_profiles_person_node_title($node) {
  $fields = array('first_name', 'middle_name_or_initial', 'last_name');
  $values = array();
  foreach ($fields as $field) {
    $items = field_get_items('node', $node, 'field_' . $field);
    if (!empty($items[0]['value'])) $values[] = $items[0]['value'];
  }
  
  $title = implode(' ', $values);
  return $title;
}