<?php

include_once 'os_subsites.features.inc';

function os_subsites_permission() {
  $items = array();

  $items['create subsites'] = array(
    'title' => t('Create Subsites'),
    'description' => t('Create sites that belong to another site.')
  );

  return $items;
}

function os_subsites_preprocess_toolbar(&$vars) {
  $space = spaces_get_space();
  if ($space && $space->group->type == 'department' && spaces_access_admin() && user_access('create subsites')) {
    $vars['toolbar']['toolbar_right']['toolbar_subsite'] = array(
      '#theme' => 'links__toolbar_subsite',
      '#links' => array(
        'add' => array(
          'title' => t('Add Subsite'),
          'href' => 'site/register',
          'description' => t('Add a subsite to the current site.'),
          'attributes' => array(
            'data-tooltip' => t('Add a subsite to the current site.'),
          ),
          'query' => array(
            'parent' => $space->group->nid,
          )
        )
      )
    );
  }
}

function os_subsites_field_attach_create_bundle($entity_type, $bundle) {
  $subsites = array('personal', 'project');
  if ($entity_type == 'node' && in_array($bundle, $subsites)) {
    if (!field_info_field('field_group_parent')) {
      $field = array(
        'active' => '1',
        'cardinality' => '1',
        'deleted' => '0',
        'entity_types' => array(),
        'field_name' => 'field_group_parent',
        'foreign keys' => array(
          'node' => array(
            'columns' => array(
              'target_id' => 'nid',
            ),
            'table' => 'node',
          ),
        ),
        'indexes' => array(
          'target_id' => array(
            0 => 'target_id',
          ),
        ),
        'locked' => '0',
        'module' => 'entityreference',
        'settings' => array(
          'handler' => 'base',
          'handler_settings' => array(
            'behaviors' => array(
              'views-select-list' => array(
                'status' => 0,
              ),
            ),
            'sort' => array(
              'type' => 'none',
            ),
            'target_bundles' => array(
              'department' => 'department',
            ),
          ),
          'target_type' => 'node',
        ),
        'translatable' => '0',
        'type' => 'entityreference',
      );
      field_create_field($field);
    }
    if (!field_info_instance($entity_type, 'field_group_parent', $bundle)) {
      $instance = array(
        'bundle' => $bundle,
        'default_value' => NULL,
        'default_value_function' => '',
        'deleted' => '0',
        'description' => '',
        'display' => array(
          'default' => array(
            'label' => 'above',
            'module' => 'entityreference',
            'settings' => array(
              'link' => FALSE,
            ),
            'type' => 'entityreference_label',
            'weight' => 6,
          ),
          'teaser' => array(
            'label' => 'above',
            'settings' => array(),
            'type' => 'hidden',
            'weight' => 0,
          ),
        ),
        'entity_type' => $entity_type,
        'field_name' => 'field_group_parent',
        'label' => 'group_parent',
        'required' => 0,
        'settings' => array(
          'behaviors' => array(
            'prepopulate' => array(
              'status' => 0,
            ),
          ),
          'user_register_form' => FALSE,
        ),
        'widget' => array(
          'active' => 1,
          'module' => 'options',
          'settings' => array(),
          'type' => 'options_select',
          'weight' => '34',
        ),
      );
      field_create_instance($instance);
    }
  }
}