<?php


/**
 * Implements hook_ctools_plugin_api().
 */
function os_boxes_ctools_plugin_api($module, $api) {
  if ($module == 'boxes' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Passthrough function so box plugin definitions are only loaded when they're needed
 * We don't need to include and process the file on every page
 */
function os_boxes_boxes_plugins() {
  require_once('os_boxes.plugins.inc');
  return _os_boxes_boxes_plugins();
}

/**
 * Implements hook_menu().
 */
function os_boxes_menu() {
  $items['os/boxes/add/%os_boxes'] = array(
    'title' => 'Add Widget',
    'page callback' => 'os_boxes_edit_widget',
    'page arguments' => array(3),
    'access callback' => 'boxes_access',
    'access arguments' => array('create', 3),
    'type' => MENU_CALLBACK,
    'file' => 'os_boxes.admin.inc',
  );

  $items['os/boxes/%os_boxes/edit'] = array(
    'title' => 'Edit Widget',
    'page callback' => 'os_boxes_edit_widget',
    'page arguments' => array(2),
    'access callback' => 'boxes_access_edit',
    'access arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
    'file' => 'os_boxes.admin.inc',
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 1,
  );

  // This item is just a helper for contextual links
  // It should always be accessible, and just not go anywhere.
  $items['os/boxes/%os_boxes'] = array(
    'access callback' => 'os_boxes_access_region',  // for contextual links
    'access arguments' => array(2),
    'page callback' => 'os_boxes_placeholder',
  ) + $items['os/boxes/%os_boxes/edit'];

  $items['os/boxes/%os_boxes/delete'] = array(
    'title' => 'Delete Widget',
    'page callback' => 'os_boxes_delete_widget',
    'page arguments' => array(2),
    'access callback' => 'boxes_access',
    'access arguments' => array('delete', 2),
    'type' => MENU_CALLBACK,
    'file' => 'os_boxes.admin.inc',
    'weight' => 2,
  );
  $items['os/boxes/%os_boxes/remove'] = array(
    'title' => 'Remove Widget',
    'page callback' => 'os_boxes_remove_widget',
    'page arguments' => array(2),
    'access callback' => 'boxes_access_admin',
    'type' => MENU_LOCAL_TASK,
    'file' => 'os_boxes.admin.inc',
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 3,
  );
  return $items;
}

/**
 * Implements hook_load().
 */
function os_boxes_load($key) {
  if ($box = boxes_box_load($key)) {
    // this is an instance;
    return $box;
  }
  if ($box = boxes_factory($key, array('delta' => os_boxes_create_delta()))) { // TODO: Build a real delta
    // this is a plugin, so create a new box
    return $box;
  }
  return false;
}

/**
 * Creates a delta from clues about the environment
 * It just needs to be unique
 */
function os_boxes_create_delta() {
  return time();  // TODO: Replace with real function
}

/**
 * Get all the boxes plugins or a plugin by name
 * @param $name
 * 		Name of the box
 */
function os_boxes_get_boxes_plugins($name = NULL){
  ctools_include('plugins');
  $boxes = ctools_get_plugins('boxes', 'plugins');
  drupal_alter('boxes_plugins', $boxes);

  if (isset($name)) {
    return isset($boxes[$name]) ? $boxes[$name] : FALSE;
  }

  return $boxes;
}

function os_boxes_os_widget($box = NULL) {
  if (isset($box)) {
    $boxes = array($box->delta => (object)$box);
    $return_single = true;
  }
  else {
    $boxes = boxes_box_load();
  }
  $widgets = array();
  foreach ($boxes as $delta => $box) {
    $bid = 'boxes-'.$delta;
    $widgets[$bid] = array(
      'module' => 'boxes',
      'delta' => $delta,
      'title' => $box->title,
      //'weight' => $box->weight,
      //'region' => $box->region,
      'info' => $box->description,
    );
  }

  if (isset($return_single)) {
    return current($widgets);
  }
  return $widgets;
}

/**
 * Implementation of hook os_widget_alter
 *
 * This function should add any parameters to the passed block that
 * will be needed in the admin user interfaces.  Including access params
 * config paths etc...
 *
 * @param $widget
 */
function os_boxes_os_widget_alter(&$widget) {
  if (isset($widget['module']) && $widget['module'] == 'boxes') {
    $box = boxes_box_load($widget['delta']);
    if (!$box) return;

    $plugin = os_boxes_get_boxes_plugins($box->plugin_key);
    if (!$plugin) return;

    $widget['info'] = $box->description;
    $widget['plugin'] = $box->plugin_key;
    if (isset($plugin['tags']))
      $widget['class'] = $plugin['tags'];

    $widget['can_edit'] = boxes_access_edit($box);  // all boxes should be editable. If they aren't, why are they a box
    $widget['path'] = 'os/boxes/'.$widget['delta'];

    // deletion is easier now.
    // just refer to the permission.
    // Generally speaking, if they can create a widget, they can delete it.
    // If they can't create it, they can't delete it either
    $widget['can_delete'] = boxes_access('delete', $box);
  }
}

function os_boxes_get_factories() {
  $plugins = os_boxes_get_boxes_plugins();
  $items = array();

  foreach ($plugins as $p => $info) {
    // title catches abstract boxes
    // factory catchs our boxes
    $dummy = new stdClass();
    $dummy->plugin_key = $p;
    if (boxes_access('create', $dummy) && isset($info['title']) && (!isset($info['factory']) || $info['factory'] !== FALSE)) {
      $items["boxes-boxes_add__$p"] = array(
        'module' => 'boxes',
        'delta' => "boxes_add__$p",
        'label' => $info['title'],
        'block_config_path' => "os/boxes/add/{$p}",
        'factory' => true,
      );
    }
  }

  return $items;
}

function os_boxes_get_tags() {
  $plugins = os_boxes_get_boxes_plugins();
  $items = array();

  foreach ($plugins as $p => $info) {
    if (isset($info['tags']) && is_array($info['tags']) && count($info['tags'])) {
      foreach ($info['tags'] as $t) {
        $items[$t] = $t;
      }
    }
  }

  return $items;
}

/**
 * When a page from these paths are linked to, they open in an overlay
 */
function os_boxes_admin_paths() {
  $paths = array(
    'os/boxes/*' => TRUE,
  );

  return $paths;
}

/**
 * Gets rid of the controls that boxes provides.
 * We want to use our own
 */
function os_boxes_preprocess_boxes_box(&$variables) {
  unset($variables['block']['controls']);
}

/**
 * Adds contextual links to our box widgets
 */
function os_boxes_block_view_alter(&$array, $block) {
  if ($block->module == 'boxes') {
    if (!is_array($array['content'])) {
      $array['content'] = array('#markup' => $array['content']);
    }

    $array['content']['#contextual_links']['box'] = array(
      'os/boxes',
      array($block->delta),
    );
  }
}

/**
 * Remove core block link from contextual
 */
function os_boxes_menu_contextual_links_alter(&$links, $router_item, $path) {
  unset($links['block-configure']);

  if (isset($links['box-remove'])) {
    $ctxs = array_keys(context_active_contexts());
    $links['box-remove']['localized_options']['query']['contexts'] = $ctxs;
  }
}



/*
 * Regional permissions
 * this may be spun off into its own module, so I'm putting it all in one place
 */

/**
 * Given a box and a set of contexts, return the region the box is in
 * This function will be called multiple times per page, so we get all the
 * regions at once and cache them in a static var.
 */
function os_boxes_get_region($box, $contexts = array()) {
  if (empty($contexts)) {
    $contexts = context_active_contexts();
  }

  $plugin = context_get_plugin('reaction', 'block');

  $blocks = &drupal_static(__FUNCTION__, array());
  if (empty($blocks)) {
    foreach ($contexts as $c) {
      foreach ($plugin->get_blocks(null, $c) as $bid => $block) {
        if ($block->module == 'boxes' && isset($block->region)){
          $blocks[$block->delta] = $block->region;
        }
      }
    }
  }

  return isset($blocks[$box->delta])?$blocks[$box->delta]:false;
}

/**
 * Given a box, return whether it can be editted based on its region.
 */
function os_boxes_access_region($box) {
  $region = os_boxes_get_region($box);

  return user_access('edit region '.$region) || user_access('edit all regions');
}

/**
 * Implementation of hook_permission()
 * Defines permissions for all the regions of the default theme
 */
function os_boxes_permission() {
  $regions = array_keys(system_region_list(variable_get('theme_default')));

  $perms = array(
    'use boxes advanced settings' => array(
      'title' => t('Use Boxes Advanced Settings'),
      'description' => t('Enable use of a boxes\' advanced settings'),
    ),
    'edit all regions' => array(
      'title' => t('Edit All Regions'),
      'description' => t('Edit the contents of all regions'),
    )
  );
  foreach ($regions as $r) {
    $perms['edit region '.$r] = array(
      'title' => t('Edit Region !region', array('!region' => $r)),
      'description' => t('Edit the contents of the region !region', array('!region' => $r)),
    );
  }

  return $perms;
}
