<?php
// $Id$


















// /**
//  * Returns the relative path a user should be redirected to on authentication.
//  *
//  * @return string $path
//  */
// function iqss_pinserver_register_pinserver_landing_path() {
//   global $user;
//   $vsites = vsite_get_vsite_by_owner($user->uid);

//   if (!vsite_vsite_exists_access($vsites)) {
//     $path = (!$vsites || (count($vsites) > 1) ? 'user' : $vsites[0]->get_absolute_url());
//   }
//   else {
//     $path = 'site/register';
//   }

//   return $path;
// }






