<?php
// $Id$

include_once (drupal_get_path('module', 'vsite_register') . '/vsite_register.form.inc');

/**
 * Implements hook_menu_alter().
 */
function iqss_pinserver_register_menu_alter(&$items) {

  // Alters page callback
  $items['site/register']['page callback'] = 'iqss_pinserver_vsite_register_form_page';
  $items['site/register']['module'] = 'iqss_pinserver_register';

  // Removes page arguments and file values.
  $remove_values = array('page arguments', 'file');
  foreach ($remove_values as $val) {
    unset($items['site/register'][$val]);
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for vsite_register_form.
 */
function iqss_pinserver_register_form_vsite_register_form_alter(&$form, $form_state, $form_id) {
  // Attaches submit and validate callbacks
  $form['#submit'][] = 'iqss_pinserver_register_submit';
  $form['#validate'][] = 'iqss_pinserver_register_validate';

  // Loads additional field(s) if user has permission
  if (user_access('create vsite content on behalf')) {
    _iqss_pinserver_register_huid_field($form);
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for vsite_users_profile_node_form.
 */
function iqss_pinserver_register_form_vsite_users_profile_node_form_alter(&$form, $form_state, $form_id) {
  if (!isset($form['buttons']['submit'])) {
    return;
  }

  // Overrides submit function from vsite_users to prevent 'home' redirect.
  $key = array_search('vsite_users_form_vsite_users_profile_node_submit', $form['buttons']['submit']['#submit']);
  if ($key) {
    $form['buttons']['submit']['#submit'][$key] = 'iqss_pinserver_register_vsite_users_profile_node_submit';
  }
}

/**
 * Submit callback; overrides vsite_users.module to prevent 'home' redirect.
 */
function iqss_pinserver_register_vsite_users_profile_node_submit($form, &$form_state) {
  if (isset($form_state['redirect'])) {
    unset($form_state['redirect']);
  }

  // Customizes confirmation message for add/edit form
  drupal_get_messages($type = NULL, $clear_queue = TRUE);
  drupal_set_message(t('Your personal information has been saved.'));
}

/**
 * Validation callback; for vsite_register_form.
 */
function iqss_pinserver_register_validate($form, &$form_state) {
  // Checks if multiple sites is limited and if site already exists
  if ($uid && !user_access('create vsite content on behalf') && count(vsite_get_vsite_by_owner($uid)) >= variable_get('openscholar_vsites_per_user', 1)) {
    $commands[] = ctools_ajax_command_html('#submit-suffix', 'The web site cannot be created. Please fix the errors and try again.');
    ctools_ajax_render($commands);
  }
}

/**
 * Submit callback; for vsite_register_form.
 */
function iqss_pinserver_register_submit($form, $state) {
  global $user;

  //new user and vsite should have already been created, check to make sure the user information is present
  if (isset($_SESSION['pinserver']['huid']) && !empty($_SESSION['pinserver']['huid']) && isset($user->uid) && !empty($user->uid)) {
    // Add user to database.
    iqss_pinserver_register_add_row($user->uid, $_SESSION['pinserver']['huid']);

    if (in_array('anonymous user', $user->roles) && !user_access('create vsite content on behalf')) {
      // log user in
      // Update the user table timestamp noting user has logged in.
      // This is also used to invalidate one-time login links.
      $user->login = time();

      db_update('users')->fields(array('login' => $user->login))->condition('uid', $user->uid, '=')->execute();
    }
  }
  else {
    error_log('WARNING: The module could not insert the new user information into the database because the user information was not supplied.');
    return;
  }

  // Removes pinserver session vars.
  pinserver_remove_session();
}

/**
 * Checks if HUID is numeric and is a new unique ID number.
 *
 * @param int $huid
 *   The HUID to validate
 *
 * @return array $errors
 *   Empty if no errors.
 */
function iqss_pinserver_register_validate_huid($huid) {
  $errors = array();

  // Verifies HUID is numeric.
  if (!is_numeric($huid)) {
    $errors[] = t('The @harvard_id must be numeric.', array('@harvard_id' => 'Harvard ID'));
  }

  // Verifies HUID does not already exist in database.
  elseif (iqss_pinserver_register_check_row($huid)) {
    $errors[] = t('The @harvard_id you have entered already exists in the database.', array('@harvard_id' => 'Harvard ID'));
  }

  return $errors;
}

/**
 * AJAX callback; for huid field
 */
function iqss_pinserver_register_ajax_validation(&$form, &$state) {
  // clear this to avoid having notices clutter the form during ajax validation
  drupal_get_messages();
  $elem = $state['triggering_element']['#name'];
  return theme('vsite_register_form_errors', array(
        'name' => $elem,
        'errors' => iqss_pinserver_register_validate_huid($state['values']['huid']),
      ));
}

/**
 * Menu callback; provides vsite_register_form for authorized users.
 */
function iqss_pinserver_vsite_register_form_page() {
  global $user;

  // Bypasses pinserver if user already owns a site or may create on behalf.
  if ($vsites = vsite_get_vsite_by_owner($user->uid) || user_access('create vsite content on behalf')) {
    // Redirects user to any existing vsite(s).
    if (!vsite_vsite_exists_access($vsites)) {
      return drupal_goto(_iqss_pinserver_register_get_redirect($vsites));
    }
    // Otherwise provides form to create a new vsite.
    else {
      return drupal_get_form('vsite_register_form');
    }
  }

  // Sends user to pinserver if not logged-in locally or via the pinserver
  if (!pinserver_check_status()) {
    return pinserver_redirect();
  }

  // Redirects pinserver-logged-in user if they don't own a vsite.
  $uid = iqss_pinserver_register_check_row();
  $vsite = vsite_get_vsite_by_owner($uid);
  if (!$vsite) {
    return drupal_get_form('vsite_register_form');
  }

  // Otherwise, redirects pinserver-logged-in user as appropriate.
  return iqss_pinserver_login_redirect($uid, $vsite);
}

/**
 * Logs in the pinserver user and redirects to any passed destination.
 */
function iqss_pinserver_login_redirect($uid, $vsite) {
  // Logs the user in based on the pinserver UID.
  $user = user_load(array('uid' => $uid));
  $user->login = time();
  db_update('users')->fields(array('login' => $user->login))->condition('uid', $user->uid, '=')->execute();

  if (isset($_GET['redirect'])) {
    // Redirects user to requested private file (or other private destination).
    drupal_goto(preg_replace('|^/|', '', $_GET['redirect']));
  }

  if (!vsite_vsite_exists_access($vsite)) {
    // Redirects user to existing vsite(s).
    drupal_goto(_iqss_pinserver_register_get_redirect($vsite));
  }

  drupal_goto('user');
}

/**
 * Writes a record to the table.
 *
 * @param int $uid
 * @param int $huid
 *
 * @return bool
 *   TRUE if database update was run.
 */
function iqss_pinserver_register_add_row($uid, $huid) {
  $object           = new stdClass();
  $object->uid      = (int)$uid;
  $object->huid     = (int)$huid;
  $object->reg_time = time();
  if (!db_query("SELECT uid FROM {iqss_pinserver_register} WHERE huid = $huid")->fetchField()) {
    drupal_write_record('iqss_pinserver_register', $object);
    return TRUE;
  }

  return FALSE;
}

/**
 * Checks if user exists in pinserver table and returns uid
 *
 * @param int $huid
 *
 * @return user id
 */
function iqss_pinserver_register_check_row($huid = NULL) {
  $id = ($huid) ? $huid : $_SESSION['pinserver']['huid'];

  if ($id) {
    return db_query("SELECT uid FROM {iqss_pinserver_register} WHERE huid = :huid", array(':huid' => $id))->fetchField();
  }

  return FALSE;
}

/**
 * Implements hook_user().
 */
function iqss_pinserver_register_user($op, &$edit, &$account, $category = NULL) {
  global $user;
  switch ($op) {
    case 'login':
      //nothing here right now
      break;

    case 'delete':
      db_delete('iqss_pinserver_register')->condition('uid', (int)$account->uid)->execute();
      break;

    case 'logout':
      pinserver_remove_session();
      break;
  }
}

/**
 * Returns the relative path a user should be redirected to on authentication.
 *
 * @return string $path
 */
function iqss_pinserver_register_pinserver_landing_path() {
  global $user;
  $vsites = vsite_get_vsite_by_owner($user->uid);

  if (!vsite_vsite_exists_access($vsites)) {
    $path = (!$vsites || (count($vsites) > 1) ? 'user' : $vsites[0]->get_absolute_url());
  }
  else {
    $path = 'site/register';
  }

  return $path;
}

/**
 * Returns the Harvard ID (HUID) of linked to the given Drupal user id (UID).
 */
function iqss_pinserver_register_get_huid($uid) {
  return db_query("SELECT huid{iqss_pinserver_register} WHERE uid = %d", (int)$uid)->fetchField();
}

/**
 * Attaches a new HUID textfield element to the given form.
 */
function _iqss_pinserver_register_huid_field(&$form) {
  $form['huid'] = array(
    '#type' => 'textfield',
    '#title' => t('Harvard ID'),
    '#size' => 35,
    '#weight' => 10,
    '#required' => FALSE,
    '#description' => t('Optional: Enter the @huid of the web site owner', array('@huid' => 'Harvard ID')),
    '#ajax' => array(
      'callback' => 'iqss_pinserver_register_ajax_validation',
      'wrapper' => 'huid-errors',
    ),
    '#field_suffix' => theme('vsite_register_form_errors', array('name' => 'huid')),
  );
}

/**
 * Provides redirect path and message for certain regstration form access conditions
 *
 * @param array $vsites
 *   Like return value of vsite_get_vsite_by_owner()
 */
function _iqss_pinserver_register_get_redirect($vsites = array()) {
  if (is_array($vsites) && count($vsites)) {
    // Clears message queue.
    drupal_get_messages();
    drupal_set_message(t('You have already registered the maximum number of web sites.'));
    if (count($vsites) == 1) {
      return $vsites[0]->get_absolute_url();
    }
    else {
      return 'user';
    }
  }

  // This should not happen unless $vsites was not passed properly or is empty array
  error_log(__FUNCTION__ . ' was called with an empty array as the first argument');
  return NULL;
}

