<?php
/**
 * @file vsite_register.module
 *
 * Provides form so users can create vsites
 */

/**
 * Implements hook_menu
 */
function vsite_register_menu() {
  $items['site/register'] = array(
    'title' => 'Create your web site',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vsite_register_form'),
    'access callback' => 'vsite_vsite_exists_access', //@TODO
    'file' => 'vsite_register.form.inc',
  );
  
  $items['admin/config/openscholar/vsite_register'] = array(
    'title' => 'Vsite Registration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vsite_register_admin_form'),
    'file' => 'vsite_register.admin.inc',
    'access arguments' => array('access administration pages'),
    //'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}


/**
 * Implements hook_block_info
 */
function vsite_register_block_info() {
  return array(
    'get_your_site_block' => array('info' => t('Vsite Registration'),'status' => 0),
  );
}

/**
 * Implements hook_block_view
 */
function vsite_register_block_view($delta = '') {
  $block = array();
  ctools_include('vsite','vsite');
  
  switch ($delta) {
    case 'get_your_site_block':
      if (vsite_vsite_exists_access()) {
        $content = l('Create your site', 'site/register', array());
        
      } elseif ($vsites = vsite_get_vsite_by_owner()) {
        
        if (count($vsites > 1)) {
          $content = l('Go to your sites', 'user');
        } else {
          $content = l('Go to your site', $vsites[0]->og->purl);
        }
      }
      
    break;
  }
  
  if (isset($content)) {
    $block['content'] = array(
      '#markup' => $content,
    );
  }
  
  return $block;
}
