<?php

include_once('scholar_blog.features.inc');

/**
 * Implementation of hook_context_links_alter().
 */
function scholar_blog_context_links_alter(&$links) {
  if (!empty($links['blog'])) {
    $links['blog']['query'] = drupal_get_destination();
  }
}

/**
 * hook link_alter (admin at the end of links)
 */
function scholar_blog_link_alter(&$links, $node){

  if (isset($links['blog_usernames_blog'])) {
    unset($links['blog_usernames_blog']);
  }
}