<?php
/**
 * @file
 *
 * Main OpenScholar module update functions.
 */

/**
 * Enable restws module
 */
function os_update_7001(&$sandbox) {
  module_enable(array('restws'));
}

/**
 * Enable the watchdog module.
 */
function os_update_7002() {
  module_enable(array('dblog'));
}

/**
 * Disable preventing anonymous cache in biblio.
 */
function os_update_7003() {
  variable_set('biblio_prevent_anon_cache', FALSE);
}
