<?php
// $Id$

/**
 * @file
 * Customizations for Gary King's website.
 */

/*
 * Implementation of hook_views_pre_build().
 *
 * Removes pager from the People page on Gary's website only.
 */
function gkplus_views_pre_build(&$view) {
  if (!_gkplus_check_purl()) {
    return;
  }
  if ($view->name !== 'os_profiles') {
    return;
  }
  $pager = $view->display_handler->get_option('pager');
  $pager['options']['items_per_page'] = 0;
  $view->display_handler->set_option('pager', $pager);
}

/**
 * Returns TRUE if the purl of the current vsite is "gkplus".
 */
function _gkplus_check_purl($purl = 'gking') {
  $vsite = vsite_get_vsite();
  return ($vsite && $vsite->group->purl == $purl);
}