<?php

/**
 * Implements hook_install().
 *
 * Sets the custom taxonomy settings to the specified vsite.
 */
function gkplus_install() {
  // Overridden taxonomy settings for this site.
  $options = array(
    'tree' => TRUE,
    'max_depth' => 3,
    'description' => TRUE,
    'nodeorder' => TRUE,
  );

  // Load the vsite and set the new variable value.
  $vsite = vsite_get_vsite(GKPLUS_SID);
  $vsite->controllers->variable->set('os_taxonomy_term_page_options', $options);
}