<?php
/**
 * @file
 * Code for the Harvard courses feature.
 */

include_once 'harvard_courses.features.inc';

/**
 * Implements hook_feeds_plugins().
 */
function harvard_courses_feeds_plugins() {
  $path = drupal_get_path('module', 'harvard_courses');
  $info = array();
  $info['FeedsTokenizedFetcher'] = array(
    'name'        => t('Token fetcher'),
    'description' => t('Create a tokenize url for fetching'),
    'handler' => array(
      'parent' => 'FeedsFetcher',
      'class'  => 'FeedsTokenizedFetcher',
      'file'   => 'harvard_courses_token_fetcher.inc',
      'path'   => $path,
    ),
  );
  return $info;
}

/**
 * Implements hook_enable().
 */
function harvard_courses_enable() {
  // TODO: Create this node usging entity metadata wrapper.
  // Create the node import - courses by department.
  $node = new stdClass();
  $node->type = 'harvard_api_importer';
  node_object_prepare($node);
  $node->title = 'Department importer';
  $node->language = LANGUAGE_NONE;

  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper->field_import_type->set('department');
  $node->field_import_type[LANGUAGE_NONE][0]['value'] = 'department';
  $node->field_base_url[LANGUAGE_NONE][0]['value'] = 'http://harvard.edu';
  node_save($node);

  // Create the node import - courses by catalog number.
  $node = new stdClass();
  $node->type = 'harvard_api_importer';
  node_object_prepare($node);
  $node->title = 'Catalog number importer';
  $node->language = LANGUAGE_NONE;
  $node->field_import_type[LANGUAGE_NONE][0]['value'] = 'cat_num';
  $node->field_base_url[LANGUAGE_NONE][0]['value'] = 'http://harvard.edu';
  node_save($node);
}

/**
 * Returning vsites nid by the import type.
 */
function haravard_courses_sites_nid_by_import_type($import_type, $search_value = array()) {
  $field = $import_type == 'cat_num' ? 'field_catalog_number' : 'field_department_id';
  $query = new entityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'vsite');

    if ($search_value) {
      $query->fieldCondition($field, 'value', $search_value, 'IN');
    }
    else {
      $query->fieldCondition($field, 'value', '', '<>');
    }

  $result = $query->execute();
  if (empty($result['node'])) {
    return;
  }

  return array_keys($result['node']);
}

/**
 * Implements hook_node_insert().
 */
function harvard_courses_node_insert($node) {
  if ($node->type != 'harvard_course') {
    return;
  }
  $wrapper = entity_metadata_wrapper('node', $node->nid);
  $vsites = haravard_courses_sites_nid_by_import_type('cat_num', array($wrapper->field_cat_number->value()));

  foreach ($vsites as $vsite) {
    og_group('node', $vsite, array('entity_type' => 'node', 'entity' => $node->nid));
  }

  $node->skip_og_membership = TRUE;
}
