<?php
/**
 * @file
 */

function os_wysiwyg_wysiwyg_editor_settings_alter(&$settings, $context) {

  // settings there are no UI options for
  $settings['gecko_spellcheck'] = true;
  drupal_add_css(drupal_get_path('module', 'os_wysiwyg').'/os_wysiwyg.css');

  // reorder buttons
  // TODO: remove when WYSIWYG module can do this for us

  // format select buttons
  $btns = explode(',', $settings['theme_advanced_buttons1']);
  $format_start = array_search('formatselect', $btns);
  $selects = array_splice($btns, $format_start, 4);
  $format_start = array_search('pasteword', $btns);
  array_splice($btns, $format_start, 0, $selects);

  // toggle toolbar button
  $toggle_start = array_search('pdw', $btns);
  $toggle = array_splice($btns, $toggle_start, 1);
  array_splice($btns, $format_start, 0, $toggle);

  $settings['theme_advanced_buttons1'] = implode(',',$btns);
}

/**
 * Implements hook_media_browser_plugins_alter.
 * Removes the default library from the Media browser. A View has replaced it.
 */
function os_wysiwyg_media_browser_plugins_alter(&$plugins) {
  unset($plugins['library']);
}

/**
 * Adds the pdw plugin to the wysiwyg
 */
function os_wysiwyg_wysiwyg_include_directory($type) {
  if ($type == 'plugins') {
    return $type;
  }
}
/*
function os_wysiwyg_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
    case 'tinymce':
      if ($version > 3) {
        return array(
          'pdw' => array(
            // A URL to the plugin's homepage.
            'url' => 'http://www.neele.name/pdw_toggle_toolbars/',
            // The full path to the native editor plugin, no trailing slash.
            // Ignored when 'internal' is set to TRUE below.
            'path' => drupal_get_path('module', 'os_wysiwyg') . '/plugins/pdw',
            // The name of the plugin's main JavaScript file.
            // Ignored when 'internal' is set to TRUE below.
            // Default value depends on which editor the plugin is for.
            'filename' => 'editor_plugin_src.js',
            // A list of buttons provided by this native plugin. The key has to
            // match the corresponding JavaScript implementation. The value is
            // is displayed on the editor configuration form only.
            'buttons' => array(
              'pdw' => t('Toggle toolbars'),
            ),
            'options' => array(
              'pdw_toggle_on' => 1,
              'pdw_toggle_toolbars' => '2,3,4',
            ),
            'load' => TRUE,
          ),
        );
      }
    break;
  }
}*/