<?php
include_once ('vsite.features.inc');
include_once ('includes/vsite.inc');

/**
 * Public Functions
 */

/**
 * Helper function to return the current vsite
 */
function vsite_get_vsite($sid = false){

  if($sid && intval($sid)){
    $vsite = spaces_load('og', $sid, false);
  }else{
    $vsite = spaces_get_space();
  }

  if($vsite && $vsite->type == 'og'){
    return $vsite;
  }

  return false;
}

/**
 * Helper function to return the current purl prefix
 *
 * @param vsite $vsite
 */
function vsite_get_purl($vsite = false){
  if (! $vsite) {
    $vsite = spaces_get_space();
  }

  if (! $vsite || ! isset($vsite->group)) {
    return "";
  }

  return $vsite->group->purl;
}

/**
 * Hooks
 */

/**
 * Implements hook_BASE_ID_form_alter().
 *
 * Runs on every node form
 */
function vsite_form_node_form_alter(&$form, &$form_state, $form_id){
  $vsite = spaces_get_space();
  $os_bundles = array_keys(os_get_bundles(true));

  if ($vsite && in_array($form['#bundle'], $os_bundles)) {
    // Set the og_group_ref value to automatically be the current active site
    $form[OG_AUDIENCE_FIELD][LANGUAGE_NONE][0]['target_id'] = array(
        '#type' => 'value',
        '#default_value' => $vsite->group->nid,
        '#field_name' => OG_AUDIENCE_FIELD,
        '#language' => LANGUAGE_NONE,
        '#entity_type' => 'node',
        '#bundle' => $form['#bundle']
    );
  }

  if (og_is_group_type('node', $form['#bundle'])) {
    // Hide the comment settings form
    $form['comment_settings']['#access'] = false;
    $form['comment_settings']['comment']['#default_value'] = 1;
  }
}

/**
 * Return the default value for the homepage path
 */
function vsite_group_default_homepage_value($entity_type, $entity, $field, $instance, $langcode){
  global $base_url;

  list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);
  // Is this a group node
  if (og_is_group_type($entity_type, $bundle)) {
    // When a site is first created it does not have a domain provider, use the
    // path provider that is attached to the entity, we can't use the standard
    // purl modifier here because the entry has not been made in the table yet
    return array(
        0 => array(
            'title' => '',
            'url' => url($entity->purl['value'], array(
                'base_url' => variable_get('purl_base_domain', $base_url),
                'absolute' => true
            ))
        )
    );
  }
}

/**
 * Make a decision about the active theme
 */
function vsite_custom_theme(){

  // See function description for why this is called here
  _vsite_purl_init();

  if ($space = spaces_get_space() && (! module_exists('cp') || ! cp_use_cp_theme())) {
    ctools_include('themes', 'os');
    $theme = os_theme_get();
    return $theme;
  }
}

/**
 * Alter the space presets to add vsite specific information
 *
 * @param
 *          $presets
 */
function vsite_spaces_presets_alter(&$presets){
  ctools_include('path', 'vsite');

  // Alter the preset to include the pathauto settings for nodes prefixed with
  // the purl path
  $pathauto_settings = _vsite_get_pathauto_settings();
  foreach ( $presets as $name => &$preset ) {
    if (substr($name, 0, 3) == "os_") {
      $preset->value['variable'] = array_merge($pathauto_settings, $preset->value['variable']);
    }
  }
}

/**
 * Alter information returned from module/theme info files
 */
function vsite_system_info_alter(&$info, $file, $type){
  static $working;

  // Only alter the vsite info file
  if ($type != 'module' || $file->name != 'vsite' || $working) {
    return;
  }

  $working = true;

  // Add the feature settings for the dynamically managed og reference fields
  if (! is_array($info['features']['field']))
    $info['features']['field'] = array();

  include_once ('vsite.features.field.inc');
  foreach ( vsite_get_group_fields() as $field => $definition ) {
    if (! in_array($field, $info['features']['field'])) {
      $info['features']['field'][] = $field;
    }
  }

  foreach (vsite_get_group_type_fields() as $field => $definition) {
    if (!in_array($field, $info['features']['field'])) {
      $info['features']['field'][] = $field;
    }
  }

  $working = false;
}

function vsite_field_default_fields_alter(&$fields) {
  if (isset($fields['node-vsite-field_group_path'])) {
    $fields += vsite_get_group_fields();
    $fields += vsite_get_group_type_fields();
  }
}

/**
 * Alter export to not include fields added through code
 */
function vsite_features_export_alter(&$export, $module_name) {
  if ($module_name == 'vsite') {
    // I don't know why this is being add as a dependency
    unset($export['dependencies']['os_publications']);
  }
}

/**
 * Implementation of hook spaces_plugins
 */
function vsite_spaces_plugins(){
  $plugins = array();
  $plugins['vsite'] = array(
    'handler' => array(
      'class' => 'vsite',
      'parent' => 'space_og'
    )
  );
  return $plugins;
}

/**
 * Implementation of hook registry_alter
 * Alter the registry to tell spaces_og groups to use the vsite plugin by
 * default
 */
function vsite_spaces_registry_alter(&$registry){

  // use the vsite plugin by default
  if (isset($registry['types']['og'])) {
    $registry['types']['og']['plugin'] = 'vsite';
  }
}

/**
 * Handles access rules for when site owner is attempting to create a another
 * site
 *
 * @return boolean
 */
function vsite_vsite_exists_access($vsites = array()){
  global $user;

  // load user's vsites. anon (uid 0) has no vsites
  if (! $vsites && $user->uid) {
    ctools_include('vsite', 'vsite');
    $vsites = vsite_get_vsite_by_owner($user->uid);
  }

  // if user has permissions to create sites, return true
  if (! user_access('create vsite content on behalf') && ! user_access('create vsite content')) {
    // drupal_set_message(t('You do not have permission to create new sites.'),
    // 'error', FALSE);
    return FALSE;
  }

  // user owns one or more sites
  if (! (count($vsites) < variable_get('os_vsites_per_user', 1) || user_access('create openscholar site on behalf of others'))) {
    // drupal_set_message(t('You have already created the maximum of %num OS
    // sites.', array('%num' => count($vsites))), 'error', FALSE);
    return FALSE;
  }

  return TRUE;
}

function vsite_permission(){
  return array(
      'create vsite content on behalf' => array(
          'title' => t('Create vsite content on behalf of other users')
      )
  );
}

/**
 * Any path in spaces is immediately disqualified from being in an overlay
 * because none
 * of them start with a wildcard.
 * They expect something like node/5/edit, when they get
 * site01/node/5/edit and fail.
 * This is rectified by putting a wildcard at the beginning to catch the space
 * modifier.
 */
function vsite_admin_paths_alter(&$paths){
  $new_paths = array();
  foreach ( $paths as $p => $b ) {
    if (strpos($p, '*/') !== 0) {
      $new_paths['*/' . $p] = TRUE;
    }
  }
  $paths = array_merge($paths, $new_paths);
}

/**
 * Return the entity reference fields to the vsite feature bundles
 */
function vsite_get_group_fields() {
  $fields = array();
  foreach (array_keys(os_get_bundles(TRUE, 'og', TRUE)) as $bundle ) {

    // Exported field: 'node-BUNDLE-og_group_ref'.
    $fields["node-{$bundle}-og_group_ref"] = array(
      'field_config' => array(
        'active' => '1',
        'cardinality' => '-1',
        'deleted' => '0',
        'entity_types' => array(),
        'field_name' => 'og_group_ref',
        'foreign keys' => array(
          'node' => array(
            'columns' => array(
              'target_id' => 'nid',
            ),
            'table' => 'node',
          ),
        ),
        'indexes' => array(
          'target_id' => array(
            0 => 'target_id',
          ),
        ),
        'locked' => '0',
        'module' => 'entityreference',
        'settings' => array(
          'handler' => 'og',
          'handler_settings' => array(
            'behaviors' => array(
              'og_behavior' => array(
                'status' => TRUE,
              ),
            ),
            'membership_type' => 'og_membership_type_default',
            'target_bundles' => array(),
          ),
          'handler_submit' => 'Change handler',
          'target_type' => 'node',
        ),
        'target_type' => 'node',
        'translatable' => '0',
        'type' => 'entityreference',
      ),
      'field_instance' => array(
        'bundle' => $bundle,
        'default_value' => NULL,
        'deleted' => '0',
        'description' => '',
        'display' => array(
          'default' => array(
            'label' => 'above',
            'module' => 'og_ui',
            'settings' => array(),
            'type' => 'og_list_default',
            'weight' => 0,
          ),
          'teaser' => array(
            'label' => 'above',
            'settings' => array(),
            'type' => 'hidden',
            'weight' => 0,
          ),
        ),
        'entity_type' => 'node',
        'field_name' => 'og_group_ref',
        'label' => 'Groups audience',
        'required' => FALSE,
        'settings' => array(
          'behaviors' => array(
            'og_widget' => array(
              'admin' => array(
                'widget_type' => 'entityreference_autocomplete',
              ),
              'default' => array(
                'widget_type' => 'options_select',
              ),
              'status' => TRUE,
            ),
          ),
          'user_register_form' => FALSE,
        ),
        'view modes' => array(
          'full' => array(
            'custom settings' => FALSE,
            'label' => 'Full',
            'type' => 'og_list_default',
          ),
          'teaser' => array(
            'custom settings' => FALSE,
            'label' => 'Teaser',
            'type' => 'og_list_default',
          ),
        ),
        'widget' => array(
          'module' => 'og',
          'settings' => array(),
          'type' => 'og_complex',
          'weight' => '0',
        ),
      ),
    );
  }

  return $fields;
}

function vsite_get_group_type_fields() {
  $groups = og_get_all_group_bundle();
  $fields = array();
  
  if(!isset($groups['node'])){
    //No group_group fields have been added yet
    //@todo create these fields when the group field is created with "hook_field_create_instance"
    return $fields;
  }

  foreach ($groups['node'] as $bundle => $title) {
    $fields['node-'.$bundle.'-field_site_address'] = array(
      'field_config' => array(
        'active' => '1',
        'cardinality' => '1',
        'deleted' => '0',
        'entity_types' => array(),
        'field_name' => 'field_site_address',
        'foreign keys' => array(
          'format' => array(
            'columns' => array(
              'format' => 'format',
            ),
            'table' => 'filter_format',
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'module' => 'text',
        'settings' => array(
          'max_length' => '255',
        ),
        'translatable' => '0',
        'type' => 'text',
      ),
      'field_instance' => array(
        'bundle' => $bundle,
        'default_value' => 'Your Town<br>Your City, State, ZIP',
        'deleted' => '0',
        'description' => '',
        'display' => array(
          'default' => array(
            'label' => 'above',
            'module' => 'text',
            'settings' => array(),
            'type' => 'text_default',
            'weight' => 3,
          ),
          'teaser' => array(
            'label' => 'above',
            'settings' => array(),
            'type' => 'hidden',
            'weight' => 0,
          ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_site_address',
        'label' => 'Site Address',
        'required' => 0,
        'settings' => array(
          'text_processing' => '0',
          'user_register_form' => FALSE,
        ),
        'widget' => array(
          'active' => 1,
          'module' => 'text',
          'settings' => array(
            'size' => '30',
          ),
          'type' => 'text_textfield',
          'weight' => '32',
        ),
      ),
    );

    $fields['node-'.$bundle.'-field_site_description'] = array(
      'field_config' => array(
        'active' => '1',
        'cardinality' => '1',
        'deleted' => '0',
        'entity_types' => array(),
        'field_name' => 'field_site_description',
        'foreign keys' => array(
          'format' => array(
            'columns' => array(
              'format' => 'format',
            ),
            'table' => 'filter_format',
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'module' => 'text',
        'settings' => array(
          'max_length' => '255',
        ),
        'translatable' => '0',
        'type' => 'text',
      ),
      'field_instance' => array(
        'bundle' => $bundle,
        'default_value' => 'Your website',
        'deleted' => '0',
        'description' => '',
        'display' => array(
          'default' => array(
            'label' => 'above',
            'module' => 'text',
            'settings' => array(),
            'type' => 'text_default',
            'weight' => 2,
          ),
          'teaser' => array(
            'label' => 'above',
            'settings' => array(),
            'type' => 'hidden',
            'weight' => 0,
          ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_site_description',
        'label' => 'Site Description',
        'required' => FALSE,
        'settings' => array(
          'text_processing' => 0,
          'user_register_form' => FALSE,
        ),
        'widget' => array(
          'module' => 'text',
          'settings' => array(
            'size' => 60,
          ),
          'type' => 'text_textfield',
          'weight' => '31',
        ),
      ),
    );

    $fields['node-'.$bundle.'-field_site_logo'] = array(
      'field_config' => array(
        'active' => '1',
        'cardinality' => '1',
        'deleted' => '0',
        'entity_types' => array(),
        'field_name' => 'field_site_logo',
        'foreign keys' => array(
          'fid' => array(
            'columns' => array(
              'fid' => 'fid',
            ),
            'table' => 'file_managed',
          ),
        ),
        'indexes' => array(
          'fid' => array(
            0 => 'fid',
          ),
        ),
        'module' => 'imagefield_crop',
        'settings' => array(
          'default_image' => 0,
          'uri_scheme' => 'public',
        ),
        'translatable' => '0',
        'type' => 'imagefield_crop',
      ),
      'field_instance' => array(
        'bundle' => $bundle,
        'deleted' => '0',
        'description' => '',
        'display' => array(
          'default' => array(
            'label' => 'above',
            'module' => 'image',
            'settings' => array(
              'image_link' => '',
              'image_style' => '',
            ),
            'type' => 'image',
            'weight' => 4,
          ),
          'teaser' => array(
            'label' => 'above',
            'settings' => array(),
            'type' => 'hidden',
            'weight' => 0,
          ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_site_logo',
        'label' => 'Site Logo',
        'required' => FALSE,
        'settings' => array(
          'alt_field' => 0,
          'file_directory' => '',
          'file_extensions' => 'png gif jpg jpeg',
          'max_filesize' => '',
          'max_resolution' => '',
          'min_resolution' => '',
          'title_field' => 0,
          'user_register_form' => FALSE,
        ),
        'widget' => array(
          'module' => 'imagefield_crop',
          'settings' => array(
            'collapsible' => 2,
            'croparea' => '500x500',
            'custom_ratio' => '',
            'enforce_minimum' => TRUE,
            'enforce_ratio' => TRUE,
            'gif_processing' => 'convert',
            'preview_image_style' => 'thumbnail',
            'progress_indicator' => 'throbber',
            'resolution' => '200x150',
            'select_maximum_area' => TRUE,
            'validate_resolution' => 0,
          ),
          'type' => 'imagefield_crop_widget',
          'weight' => '33',
        ),
      ),
    );
  }

  return $fields;
}

/**
 * @function _vsite_purl_init()
 *
 * Calls purl_init. This is used during hook_custom_theme, so that we can
 * get the space earlier.
 *
 * Following a cache clear, the spaces presets need rebuilding. At some
 * point in this process, l() is called to put a link in the description
 * of a field in image. If l() tries to theme the link it creates,
 * drupal_initialize_theme is run, defeating the purpose of hook_custom_theme.
 *
 * This function prevents l() from initalizing the theme by setting theme_link
 * to false, running purl_init, and then restoring theme_link to its original
 * value.
 *
 * This fixes the theme problem after a cache clear. May have other unforseen
 * consequences.
 */
function _vsite_purl_init(){
  // hack alert!
  global $conf;
  $theme_link = isset($conf['theme_link']) ? $conf['theme_link'] : NULL;
  $conf['theme_link'] = FALSE;

  purl_init();

  if (isset($theme_link)) {
    $conf['theme_link'] = $theme_link;
  }
  else {
    unset($conf['theme_link']);
  }
}

/** 
 * Implements hook_menu_alter()
 * Using this function to remove the "Groups" link
 * from the users 'edit' form
 */
function vsite_menu_alter(&$items) {
	$items['user/%user/edit/groups']['access callback'] = false;
}// end function

/**
 * Function to load all the sites the user belongs to
 */
function vsite_load_user_sites($userId) {
	$sites = array();
	$sitesArray = array();
	// grab their sites 
	$vsites = vsite_get_vsite_by_owner($userId);
	// create each site as a link
	foreach($vsites as $site) {
		$sites=array('#title'=>$site->group->title, '#type'=>'link','#href'=>$site->get_absolute_url());
		// prepare them for theme_list_item
		$sitesArray[] = array('data'=>drupal_render($sites));
	}// end foreach
	
	return $sitesArray;
}// end function

/**
 * Implementation of hook_user_view_alter()
 * Altering the user view to remove history, groups and other groups
 * also altering to add in "My Websites" for all sites the user belongs to.
 */
function vsite_user_view_alter(&$build) {
	global $user;
	
	// Removal section
		// remove the "history" and "member for" info if it's there
		if(isset($build['summary'])) {
			unset($build['summary']);
		}// end if
		// remove the og_user_group_ref
		if(isset($build['og_user_group_ref'])) {
			$build['og_user_group_ref']['#access'] = false;
		}// end if
		// remove the og_other_user_group_ref
		if(isset($build['og_other_user_group_ref'])) {
			$build['og_other_user_group_ref']['#access'] = false;
		}// end if
	// 

		// make sure they're logged in
		if($user->uid) {
		// Additions section
			// load their link created vsites
			$vsites = (vsite_load_user_sites($build['#account']->uid));
	
			// in d6 a plural or singular was used in order to apply the correct CSS selector to the list
			// retain that functionality
			if(count($vsites)>1) {
				$cssSelector = array('class'=>'plural');
			}else{
				$cssSelector = array('class'=>'single');
			}// end if
			
			// pass the items to theme_item_list
			$vsitesList = theme_item_list(array('items'=>$vsites, 'title'=>'','type'=>'ul','attributes'=>$cssSelector));
			
			// set a new field
			$build['web_sites'] = array(
			      	'#title' => 'My Websites',
			      	'#type' => 'user_profile_item', 
					'#markup' => $vsitesList,
   		 	);//
   		 //
	}// end if
}// end function

/**
 * Implement hook_mail_alter
 * function to alter some of the emails that are sent out
 * to users based on certain actions
 * 
 */
function vsite_mail_alter(&$message) {
	// ToDo
}// end function
