<?php

function hwpi_preprocess_page(&$vars) {
  if (_is_hwpi_theme()) {
    $vars['page']['branding_header']['hwpi'] = _hwpi_branding_header();
    $vars['page']['branding_footer']['hwpi'] = _hwpi_branding_footer();
  }
}

function _is_hwpi_theme() {
  $themes = list_themes();
  if (isset($themes[$GLOBALS['theme']])) {
    $t = $themes[$GLOBALS['theme']];
    if (isset($t->base_themes) && isset($t->base_themes['hwpi_basetheme'])) {
      return true;
    }
  }
  return false;
}

function _hwpi_branding_header() {
  $header = array();
  $header['left_container'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'branding-left',
      )
    ),
    'img' => array(
      '#theme' => 'link',
      '#path' => 'http://www.harvard.edu',
      '#text' => theme('image', array('path' => drupal_get_path('theme', 'hwpi_basetheme') . '/images/harvard-logo.png', 'width' => 259, 'height' => 35)),
      '#options' => array(
        'external' => TRUE,
        'html' => TRUE,
        'attributes' => array(),
      )
    ),
  );
  $sites = _hwpi_get_ancestry();
  $links = array();
  foreach ($sites as $path => $title) {
    $links[] = l($title, $path);
  }
  $header['right_container'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'branding-right',
      )
    ),
    'sitecrumbs' => array(
      '#type' => 'markup',
      '#markup' => implode(' | ', $links)
    ),
  );

  return $header;
}

function _hwpi_get_ancestry() {
  $sites = array();
  if ($vsite = spaces_get_space()) {
    $group = $vsite->group;
    while (isset($group->field_group_parent) && $group->field_group_parent) {
      $d = field_get_items('node', $group, 'field_group_parent');
      $vsite = vsite_get_vsite($d[0]['target_id']);
      $group = $vsite->group;
      $sites[$vsite->get_absolute_url()] = $group->title;
    }
  }

  $sites['http://www.harvard.edu'] = 'HARVARD.EDU';
  return $sites;
}

function _hwpi_branding_footer() {
  $footer = array();
  $footer['hwpi_container'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'copyright',
      )
    ),
    'copyright' => array(
      '#markup' => t('<span class="harvard-copyright">Copyright &copy; 2013 The President and Fellows of Harvard College</span> | !privacy | !access', array(
        '!privacy' => l('Privacy', 'http://www.harvard.edu/privacy-statement'),
        '!access' => l('Accessibility', 'http://accessibility.harvard.edu/')
      ))
    )
  );

  return $footer;
}

function hwpi_block_view_alter(&$render, $block) {
  if ($block->delta == 'site-search' && _is_hwpi_theme()) {
    unset($render['content']['search_block_form']['#title_display']);
  }
}
