<?php

/**
 * Implement hook_form_FORM_ID_alter
 * Need to hook into the openscholar settings form
 * to allow admins to set the global Google Analytics ID
 * 
 */
function os_ga_form_os_settings_form_alter(&$form, &$form_state, $form_id) {
	$form['os_ga_global_id'] = array(
		'#type' => 'textfield',
  		'#title' => t('Enter your Google Analytics ID'),
  		'#size' => 20,
  		'#maxlength' => 255,
  		'#default_value' => variable_get('os_ga_global_id', ''),
  		'#description' => t("Entering your ID this will enable the sending of your OpenScholar sitewide page and visitor data to your Google Analytics account. Go to the <a href=\"http://www.google.com/analytics/\">Google Analytics site</a> to set one up. Your ID will be in the format UA-XXXXXXX-XX."),
  		'#element_validate' => array('os_ga_analytics_id_validate')
	);
}// end function

/**
 * Implementation hook os_ga_cp_settings()
 * @return array
 */
function os_ga_cp_settings(){
  	$a_settings = array();
	
  	$a_settings['os_ga_google_analytics_id'] = array(
    	'form' => array(
      	'#type' => 'textfield',
      	'#title' => t('Enter your Google Analytics ID'),
      	'#size' => 20,
      	'#maxlength' => 255,
      	'#default_value' => variable_get('os_ga_google_analytics_id',''),
      	'#description' => t("Entering your ID this will send page and visitor data to your Google Analytics account. Go to the <a href=\"http://www.google.com/analytics/\">Google Analytics site</a> to set one up. Your ID will be in the format UA-XXXXXXX-XX."),
      	'#element_validate' => array('os_ga_analytics_id_validate')
  	),
  		'group' => array(
  	  	'#id' => 'ga',
  	  	'#title' => t('Google Analytics'),
  	  	'#weight' => 0,
  	),
  	);
  	return $a_settings;
}

function os_ga_init() {

	$ga_vars = _os_ga_ga_id_vars();
	if(!count($ga_vars)) return;  //if no ga ids are saved, then return
	
	global $user;
  	// Build tracker code for footer.
  	$script = '';
  	// check to see if both global and site specific GA accounts are set
  	if((!empty($ga_vars['global_id']))&&(!empty($ga_vars['os_id']))) {
  		
  		// set both to be tracked
  		$script .= '_gaq.push(["_setAccount", ' . drupal_json_encode($ga_vars['os_id']) . ']);';
	 	$script .= '_gaq.push(["_trackPageview"]);';
	  	// add in our globak account as well
	  	$script .= '_gaq.push(["b._setAccount", ' . drupal_json_encode($ga_vars['global_id']) . ']);';
		$script .= '_gaq.push(["b._trackPageview"]);';
	  	// finish up the script
		$script .= '(function() {';
	  	$script .= 'var ga = document.createElement("script");';
	  	$script .= 'ga.type = "text/javascript";';
	  	$script .= 'ga.async = true;';
	  	$script .= 'ga.src = ("https:" == document.location.protocol ? "https://ssl" : "http://www") + ".google-analytics.com/ga.js";';
	  	$script .= 'var s = document.getElementsByTagName("script")[0];';
	  	$script .= 's.parentNode.insertBefore(ga, s);';
	  	$script .= '})();';
  	}elseif(!empty($ga_vars['global_id'])){ 
  		//global pageTracker object
	  	$script = 'var _gaq = _gaq || [];';
	  	$script .= '_gaq.push(["_setAccount", ' . drupal_json_encode($ga_vars['global_id']) . ']);';
		//pass segmentation data to pageTrackerGlobal account
	  	if (!empty($segmentation)) {
	    	$script .= $segmentation;
	  	}// end if
	  	$script .= '_gaq.push(["_trackPageview"]);';
	  	$script .= '(function() {';
	  	$script .= 'var ga = document.createElement("script");';
	  	$script .= 'ga.type = "text/javascript";';
	  	$script .= 'ga.async = true;';
	  	$script .= 'ga.src = ("https:" == document.location.protocol ? "https://ssl" : "http://www") + ".google-analytics.com/ga.js";';
	  	$script .= 'var s = document.getElementsByTagName("script")[0];';
	  	$script .= 's.parentNode.insertBefore(ga, s);';
	  	$script .= '})();';
	 }elseif(!empty($ga_vars['os_id'])){ 
	 	//vsite pageTracker object
	  	$script .= 'var _gaq = _gaq || [];';
	  	$script .= '_gaq.push(["_setAccount", ' . drupal_json_encode($ga_vars['os_id']) . ']);';
	 	$script .= '_gaq.push(["_trackPageview"]);';
	  	// add in our globak account as well
	  	// $script .= '_gaq.push(["b._setAccount", ' . drupal_json_encode($globalAccount) . ']);';
		// $script .= '_gaq.push(["b._trackPageview"]);';
	  	// finish up the script
		$script .= '(function() {';
	  	$script .= 'var ga = document.createElement("script");';
	  	$script .= 'ga.type = "text/javascript";';
	  	$script .= 'ga.async = true;';
	  	$script .= 'ga.src = ("https:" == document.location.protocol ? "https://ssl" : "http://www") + ".google-analytics.com/ga.js";';
	  	$script .= 'var s = document.getElementsByTagName("script")[0];';
	  	$script .= 's.parentNode.insertBefore(ga, s);';
	  	$script .= '})();';
	 }else{
	 	$script = '';
	 } // default to out global account
	 
  	if (strlen($script)){
    	//code snippet goes in header by default
   	 	drupal_add_js($script, 'inline', variable_get('vsite_ga_scope' , 'header'));
  	}// end if
}

/**
 * Check for global and site-specific Google Analytics ID variables
 */
function _os_ga_ga_id_vars(){
	$ga_vars = array();
  	//global id
  	// load in the spaces info
  	//global id
  	
  	$spaces = spaces_get_space();
  	
  	if ($spaces) {
    	//if (strlen($spaces->controllers->variable->get('vsite_ga_google_analytics_id', 'original'))) {
    	// check for the global GA account set from the admin bar
  		if($global_id = variable_get('os_ga_global_id', '')) {
      		if (strlen($global_id)) {
      			$ga_vars['global_id'] = $global_id;
      			
      		}
    	}

    	// check for the site specific GA account set from the users Settings 
    	if($local_id = variable_get('os_ga_google_analytics_id', '')) {
      		if (strlen($local_id)) {
        		$ga_vars['os_id'] = $local_id;
        		
      		}
    	}
  	}else {
    	//if($global_id = variable_get('vsite_ga_google_analytics_id', '')) {
    	// no personal GA account nor spaces set, grab the global GA account
  		if($global_id = variable_get('os_ga_global_id', '')) {
      		if (strlen($global_id)) {
        		$ga_vars['global_id'] = $global_id;
      		}
    	}
  	}
  	return $ga_vars;
}

/**
 * Validates a user-entered GA string
 */
function os_ga_analytics_id_validate($element, $form_state) {
	$pattern = '/^UA-[0-9]+-[0-9]{1,2}$/';
	if($element['#value'] && !preg_match($pattern, trim($element['#value']))) {
		form_error($element, t('This field does not follow the correct format.'));
	}

}
