<?php
/**
 * @file
 */

include_once('os_image_gallery.features.inc');


/**
 * Implements hook_contextual_links_view_alter
 * 
 * OS and media_gallery both add contextuals.  Clean that up.
 */
function os_image_gallery_contextual_links_view_alter(&$element, $items) {
  if (isset($element['#contextual_links']['media_gallery'])) {
    unset($element['#links']['media-gallery-edit']);
    unset($element['#links']['media-gallery-remove']);
  }
}



/**
 * Implements hook_form_FORM_ID_alter().
 * 
 * Removes block option from media_gallery node edit.  OS blocks are managed by layout CP.  This shouldn't be exception.
 */
function os_image_gallery_form_media_gallery_node_form_alter(&$form, &$form_state) {
  $form['block']['#type'] = 'hidden';
}

/**
 * Implements hook_module_implements_alter().
 * 
 * Makes sure that os_image_gallery alters the media_gallery form after media_gallery
 */
function os_image_gallery_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter' && isset($implementations['media_gallery'], $implementations['os_image_gallery'])) {
    $os_image_gallery = $implementations['os_image_gallery'];
    unset($implementations['os_image_gallery']);
    $implementations['os_image_gallery'] = $os_image_gallery;
  }
}