<?php


/**
 * Implementation of hook_ctools_plugin_api().
 */
function os_boxes_ctools_plugin_api($module, $api) {
  if ($module == 'boxes' && $api == 'plugins') {
    return array('version' => 1);
  }
  if ($module == "boxes" && $api == "box") {
    return array("version" => 1);
  }
}

/**
 * Implementation of hook_boxes_plugins().
 */
function os_boxes_boxes_plugins() {
  $info = array();
  $path = drupal_get_path('module', 'os_boxes') .'/plugins';

  $info['os_boxes_default'] = array(
    'handler' => array(
      'class' => 'os_boxes_default',
      'file' => 'os_boxes_default.inc',
      'path' => $path,
      'parent' => 'box',
    ),
  );
  $info['os_boxes_simple'] = array(
    'title' => 'Text',
    'description' => 'Simple custom text',
    'tags' => array('Content','Text'),
    'handler' => array(
      'parent' => 'box',
      'class' => 'boxes_simple',
      'file' => 'boxes_simple.inc',
      'path' => drupal_get_path('module','boxes').'/plugins',
    ),
  );

  $info['os_boxes_addthis'] = array(
    'title' => 'Addthis',
    'description' => 'Social media links',
    'tags' => array('Social','Addthis'),
    'handler' => array(
      'class' => 'os_boxes_addthis',
      'file' =>  'os_boxes_addthis.inc',
      'path' => $path,
      'parent' => 'os_boxes_default',
    ),
  );

  $info['os_boxes_feedreader'] = array(
    'title' => 'Feed Reader',
    'description' => 'List of feed items',
    'tags' => array('Content','Social','Feed'),
    'handler' => array(
      'class' => 'os_boxes_feedreader',
      'file' => 'os_boxes_feedreader.inc',
      'path' => $path,
      'parent' => 'os_boxes_default',
    ),
  );

  $info['os_boxes_gallery'] = array(
    'title' => 'Image Gallery',
    'description' => 'List of images',
    'tags' => array('Media', 'Image'),
    'handler' => array(
      'class' => 'os_boxes_gallery',
      'file' => 'os_boxes_gallery.inc',
      'path' => $path,
      'parent' => 'os_boxes_default',
    ),
  );

  $info['os_boxes_slideshow'] = array(
    'title' => 'Slideshow Gallery',
    'description' => 'Display gallery as a slideshow',
    'tags' => array('Media','Slideshow'),
    'handler' => array(
      'class' => 'os_boxes_slideshow',
      'file' => 'os_boxes_slideshow.inc',
      'path' => $path,
      'parent' => 'os_boxes_default',
    ),
  );

  $info['os_boxes_rss'] = array(
    'title' => 'RSS feed',
    'description' => 'RSS feed ??',
    'tags' => array('Social','Feed'),
    'handler' => array(
      'class' => 'os_boxes_feedreader',
      'file' => 'os_boxes_feedreader.inc',
      'path' => $path,
      'parent' => 'os_boxes_default',
    ),
  );

  $info['os_boxes_twitterfeed'] = array(
    'title' => 'Twitter feed CUSTOM BOX',
    'description' => 'List of latest tweets',
    'tags' => array('Social','Feed','Twitter'),
    'handler' => array(
      'class' => 'os_boxes_twitterfeed',
      'file' => 'os_boxes_twitterfeed.inc',
      'path' => $path,
      'parent' => 'os_boxes_default',
    ),
  );

  $info['os_boxes_cclicense'] = array(
    'title' => 'CC License',
    'description' => 'Displays CC license widget',
    'tags' => array('Misc','License'),
    'handler' => array(
      'class' => 'os_boxes_cclicense',
      'file' => 'os_boxes_cclicense.inc',
      'path' => $path,
      'parent' => 'os_boxes_default',
    ),
  );


  $info['os_boxes_node'] = array(
    'title' => 'Post in a box',  // i.e. view
    'description' => 'Displays the content of a post in the widget',
    'tags' => array('Content','Post'),
    'handler' => array(
      'class' => 'os_boxes_node',
      'file' => 'os_boxes_node.inc',
      'path' => $path,
      'parent' => 'os_boxes_default',
    ),
  );

  $info['os_boxes_bio'] = array(
    'title' => 'Bio Box',  // i.e. view
    'description' => 'Displays biography blurb',
    'tags' => array('Misc','Bio'),
    'handler' => array(
      'class' => 'os_boxes_bio',
      'file' => 'os_boxes_bio.inc',
      'path' => $path,
      'parent' => 'os_boxes_node',
    ),
  );

  $info['os_boxes_oembed'] = array(
    'title' => 'Media Embed',  // i.e. view
    'description' => 'Embed Media',
    'tags' => array('Media'),
    'handler' => array(
      'class' => 'os_boxes_oembed',
      'file' => 'os_boxes_oembed.inc',
      'path' => $path,
      'parent' => 'os_boxes_default',
    ),
  );

  $info['os_boxes_shields'] = array(
    'title' => 'Shield',
    'description' => 'Department Shield',
    'tags' => array('Misc','Shield'),
    'handler' => array(
      'class' => 'os_boxes_shields',
      'file' => 'os_boxes_shields.inc',
      'path' => $path,
      'parent' => 'os_boxes_default',
    )
  );

  $info['os_boxes_booktoc'] = array(
    'title' => 'Book Table of Contents',
    'description' => 'Table of Contents',
    'tags' => array('Content','Book'),
    'handler' => array(
      'class' => 'os_boxes_booktoc',
      'file' => 'os_boxes_booktoc.inc',
      'path' => $path,
      'parent' => 'os_boxes_default',
    )
  );
  
  $info['os_boxes_simpleview_list'] = array(
    'title' => 'List of posts',
    'description' => '',
    'tags' => array(
      'Content'
    ),
    'handler' => array(
      'class' => 'os_boxes_simpleview_list',
      'file' => 'os_boxes_simpleview_list.inc',
      'path' => $path,
      'parent' => 'spaces_simpleviews_post_list'
    ),
  );
  
  foreach ($info as $key => $block) {
  	if(!isset($info[$key]['access'])){
  		$info[$key]['access'] = "cp_access_cp";
  	}
  }

  return $info;
}

/**
 * hook vsite_sidgets
 *
 * This function translates the box intances and the box defintions into vsite widgets for use in the
 * openscholar layout structure
 */
function os_boxes_vsite_widgets(){
  $items = array();

  /**
   * Avalible block defintions
   */
  ctools_include('plugins');
  $plugins = ctools_get_plugins('boxes', 'plugins');

  $items = array();
  foreach ( $plugins as $key => $info ) {
  	//Call access function
  	if(!$info['access'] || !call_user_func($info['access'])) continue;
  	
    if (isset($info['title'])) {
      $items["boxes-boxes_add__$key"] = array(
        'module' => 'boxes',
        'delta' => "boxes_add__$key",
        'weight' => -10,
        'region' => $info['region']?$info['region']:false,
        'label' => $info['title'],
        'block_config_path' => "cp/osboxes/nojs/boxes_add__{$key}/configure",
      );
      if (is_array($plugins[$key]['tags']) && count($plugins[$key]['tags'])) {
        $items["boxes-boxes_add__$key"]['tags'] = $plugins[$key]['tags'];
      }

      if ($info['factory_path']) {
        $items["boxes-boxes_add__$key"]['block_config_path'] = $info['factory_path']."/modal/box/$key";
      }
    }
  }

  /**
   * Block instances for this site
   */
  $boxes = boxes_load();
  foreach ($boxes as $box) {
  	if(!$box->delta) continue;
    $items["boxes-{$box->delta}"] = os_boxes_get_vsite_widget($box);
  }

  return $items;
}

/**
 * Return a widget array when passed a box instance
 */
function os_boxes_get_vsite_widget($box, $weight = 0, $region = false){
	ctools_include('plugins');
  $plugins = ctools_get_plugins('boxes', 'plugins');

	$a_wgt = array(
    'module' => 'boxes',
    'delta' => $box->delta,
    'weight' => $weight,
    'region' => $region,
    'label' => $box->description,
    'cache' => BLOCK_CACHE_CONTENT_CACHE,
	  'block_config_path' => "cp/osboxes/".($plugins[$box->plugin_key]['popup']?$plugins[$box->plugin_key]['popup']:'nojs')."/{$box->delta}/configure",
  );

  if(!$region && isset($box->region)){
    $a_wgt['region'] =$box->region;
  }

  if (is_array($plugins[$box->plugin_key]['tags'])) {
    $a_wgt['tags'] = $plugins[$box->plugin_key]['tags'];
  }

  if (isset($plugins[$box->plugin_key]['icon_path'])) {
    $a_wgt['icon_path'] = $plugins[$box->plugin_key]['icon_path'];
  }

  if (is_a($box, 'os_boxes_modalframe')) {
    $a_wgt['block_config_path'] = $box->get_config_path();
  }

  return $a_wgt;
}

/**
 * Implementation of hook_menu().
 */
function os_boxes_menu() {

  $items['cp/osboxes/%ctools_js/%/configure'] = array(
    'title' => 'Configure this Widget',
    'page callback' => 'os_boxes_box_modal',
    'page arguments' => array( 2,3),
    'access callback' => 'os_boxes_cp_layout_configurable',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Determine if this box has a form, return true if it does, false otherwise
 */
function os_boxes_cp_layout_configurable($delta){

  if ($delta && strpos($delta, 'boxes_add__') !== 0) {
  	//Box instance
    if ($box = boxes_load($delta)) {
      return ($box->options_form())?true:false;
    }
  }else{
  	//New Box
  	$plugin_key = str_replace('boxes_add__', '', $delta);
    if ($box = boxes_factory($plugin_key)) {
      return ($box->options_form())?true:false;
    }
  }
  return false;
}

/**
 * A modal callback for configuring a box
 */
function os_boxes_box_modal($js = NULL, $delta){
  module_load_include('inc', 'boxes', 'boxes.admin');
  module_load_include('inc', 'boxes', 'plugins/boxes_box');

  $b_newbox = (strpos($delta,"boxes_add__") === 0);

  if($b_newbox){
    $plugin_key = str_replace('boxes_add__', '', $delta);
    $delta = os_boxes_create_delta();
	  $box = boxes_factory($plugin_key, array(
	    'delta' => $delta
	  ));
  }else{
  	$box = boxes_load($delta);
  }

  // Fall back if $js is not set.
  ctools_include('form');
  if (!$js) {
    $form_state = array('box' => $box);
    if (module_exists('modalframe')) {
      modalframe_child_js();
    }
    return ctools_build_form('boxes_box_form', $form_state);
  }

  ctools_include('modal');
  ctools_include('ajax');


  $form_state = array(
    'box' => $box,
    'plugin_key' => $box->plugin_key,
    'custom_action' => TRUE,
    'ajax' => 'TRUE',
    'no_redirect' => TRUE
  );

  $output = ctools_modal_form_wrapper("boxes_box_form", $form_state);

  if (empty($output)) {
    $output = array();
    $output[] = ctools_modal_command_dismiss();
  }
  else {
    $output[] = ctools_ajax_command_after('#modal-content #edit-submit','<input class="form-submit close" onClick="$(\'div.modal-header a.close\').click(); return false;" value="Cancel" />');
  }

  if(isset($form_state['js commands']) && is_array($form_state['js commands'])){
  	$output = array_merge($form_state['js commands'],$output);
  }

  ctools_ajax_render($output);
}

function os_boxes_create_delta() {
    $identifier = (module_exists('spaces') && $space = spaces_get_space()) ? "{$space->type}-{$space->id}" : 'box';
    $hash = boxes_create_hash($identifier);
    $delta = $identifier . "-" . $hash;
    return $delta;
}

/**
 * Implementation of form alter
 * @param $form
 * @param $form_state
 */
function os_boxes_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id){
  	case "boxes_box_form":
  		//Allow each box to handle it's own validation && submission
  		$form['#validate'][] = 'os_boxes_box_validate';
  		$form['#submit'][] = 'os_boxes_box_submit';
  	break;
  }
}

/**
 * Allow each box to validate it's form
 *
 * @param unknown_type $form
 * @param unknown_type $form_state
 */
function os_boxes_box_validate($form, &$form_state){

	ctools_include('plugins');
	$box_class = ctools_plugin_load_class('boxes', 'plugins', $form_state['values']['plugin_key'], 'handler');
	if ($box_class && is_callable("{$box_class}::options_validate")) {
		call_user_func(array($box_class,'options_validate'),$form, $form_state);
	}
}

/**
 * Allow each box to implement a submit handler
 *
 * @param unknown_type $form
 * @param unknown_type $form_state
 */
function os_boxes_box_submit(&$form, &$form_state){

	ctools_include('plugins');
	$box_class = ctools_plugin_load_class('boxes', 'plugins', $form_state['values']['plugin_key'], 'handler');
  if ($box_class && is_callable("{$box_class}::options_submit")) {
    call_user_func(array($box_class,'options_submit'),$form, $form_state);
  }
}
