<?php
// $Id$


/**
 * @file
 * Code for the OS announcements feature module.
 */

include_once ('os_announcements.features.inc');

/**
 * Implements hook_process_hook() for node.
 *
 * Customizes $submitted for announcement nodes as just "M D, YYYY"
 */
function os_announcements_process_node(&$vars) {
  if ($vars['type'] !== 'announcement') {
    return;
  }
  // Build the submitted variable used by default in node templates
  $pubdate = format_date($vars['created'], 'custom', 'F j, Y');
  // Publication date, formatted with time element
  $vars['submitted'] = '<time datetime="' . $vars['datetime'] . '" pubdate="pubdate">' . $pubdate . '</time>';
}

/**
 * Implements hook_vsite_og_node_type_info().
 */
function os_announcements_vsite_og_node_type_info() {
  return array(
    'announcement' => 'group content',
  );
}

