<?php

/**
 * Apply a set of blocks to a vsite's context
 *
 * @param string $context
 * @param array $blocks
 */
function vsite_layout_context_set($context, $blocks){

  $vsite = spaces_get_space();

  if($vsite && isset($vsite->controllers->context)){
    $vsite->controllers->context->set($context.":reaction:block", array('blocks' => $blocks));
    return true;
  }

  return false;
}

/**
 * Reverts a individual context back to defaults
 *
 * @param string $context
 *
 * @return boolean Success
 */
function vsite_layout_context_revert($context){

  $vsite = spaces_get_space();

  if($vsite && isset($vsite->controllers->context)){
    $vsite->controllers->context->del($context.":reaction:block");
    return true;
  }

  return false;
}